/* Domain definitions */
CREATE DOMAIN G2_GBUN_00_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN G2_GBUN_01_HCODE AS VARCHAR(5);
CREATE DOMAIN G2_GBUN_02_GCODE AS VARCHAR(5);
CREATE DOMAIN G2_GBUN_03_GNAME AS VARCHAR(20);
CREATE DOMAIN G2_GBUN_04_GMEMO AS TimeStamp;

/* Table: G2_GBUN, Owner: SYSDBA */

CREATE TABLE G2_GBUN 
(
  ID	G2_GBUN_00_ID,
  HCODE	G2_GBUN_01_HCODE,
  GCODE	G2_GBUN_02_GCODE,
  GNAME	G2_GBUN_03_GNAME,
  GMEMO	G2_GBUN_04_GMEMO
);

CREATE ASCENDING INDEX G2_GBUN_ ON G2_GBUN (ID);
CREATE ASCENDING INDEX G2_GBUN_HCODE ON G2_GBUN (HCODE);
CREATE ASCENDING INDEX G2_GBUN_GCODE ON G2_GBUN (GCODE);

CREATE GENERATOR G2_GBUN_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER G2_GBUN_ID_TNO FOR G2_GBUN 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(G2_GBUN_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;





/* Domain definitions */
CREATE DOMAIN G2_GGWO_00_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN G2_GGWO_01_HCODE AS VARCHAR(5);
CREATE DOMAIN G2_GGWO_02_GUBUN AS VARCHAR(5);
CREATE DOMAIN G2_GGWO_03_JUBUN AS VARCHAR(6);
CREATE DOMAIN G2_GGWO_04_PUBUN AS VARCHAR(2);
CREATE DOMAIN G2_GGWO_05_SCODE AS VARCHAR(1);
CREATE DOMAIN G2_GGWO_06_GCODE AS VARCHAR(5);
CREATE DOMAIN G2_GGWO_07_OCODE AS VARCHAR(5);
CREATE DOMAIN G2_GGWO_08_GNAME AS VARCHAR(24);
CREATE DOMAIN G2_GGWO_09_GPOSA AS VARCHAR(20);
CREATE DOMAIN G2_GGWO_10_GNUMB AS VARCHAR(12);
CREATE DOMAIN G2_GGWO_11_GUPER AS VARCHAR(20);
CREATE DOMAIN G2_GGWO_12_GJOMO AS VARCHAR(20);
CREATE DOMAIN G2_GGWO_13_GPOST AS VARCHAR(7);
CREATE DOMAIN G2_GGWO_14_GADD1 AS VARCHAR(44);
CREATE DOMAIN G2_GGWO_15_GADD2 AS VARCHAR(44);
CREATE DOMAIN G2_GGWO_16_GTEL1 AS VARCHAR(4);
CREATE DOMAIN G2_GGWO_17_GTEL2 AS VARCHAR(20);
CREATE DOMAIN G2_GGWO_18_GFAX1 AS VARCHAR(4);
CREATE DOMAIN G2_GGWO_19_GFAX2 AS VARCHAR(20);
CREATE DOMAIN G2_GGWO_20_GRAT1 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G2_GGWO_21_GRAT2 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G2_GGWO_22_GRAT3 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G2_GGWO_23_GRAT4 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G2_GGWO_24_GRAT5 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G2_GGWO_25_GRAT6 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G2_GGWO_26_GRAT7 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G2_GGWO_27_GRAT8 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G2_GGWO_28_GRAT9 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G2_GGWO_29_GQUT1 AS DOUBLE PRECISION
	  DEFAULT 0;
CREATE DOMAIN G2_GGWO_30_GPPER AS VARCHAR(10);
CREATE DOMAIN G2_GGWO_31_GBIGO AS VARCHAR(40);
CREATE DOMAIN G2_GGWO_32_NAME1 AS VARCHAR(40);
CREATE DOMAIN G2_GGWO_33_NAME2 AS VARCHAR(40);
CREATE DOMAIN G2_GGWO_34_YESNO AS VARCHAR(5);
CREATE DOMAIN G2_GGWO_35_GPHON AS VARCHAR(15);
CREATE DOMAIN G2_GGWO_36_EMAIL AS VARCHAR(15);
CREATE DOMAIN G2_GGWO_37_GSSUM AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN G2_GGWO_38_GMEMO AS TimeStamp;

/* Table: G2_GGWO, Owner: SYSDBA */

CREATE TABLE G2_GGWO 
(
  ID	G2_GGWO_00_ID,
  HCODE	G2_GGWO_01_HCODE,
  GUBUN	G2_GGWO_02_GUBUN,
  JUBUN	G2_GGWO_03_JUBUN,
  PUBUN	G2_GGWO_04_PUBUN,
  SCODE	G2_GGWO_05_SCODE,
  GCODE	G2_GGWO_06_GCODE,
  OCODE	G2_GGWO_07_OCODE,
  GNAME	G2_GGWO_08_GNAME,
  GPOSA	G2_GGWO_09_GPOSA,
  GNUMB	G2_GGWO_10_GNUMB,
  GUPER	G2_GGWO_11_GUPER,
  GJOMO	G2_GGWO_12_GJOMO,
  GPOST	G2_GGWO_13_GPOST,
  GADD1	G2_GGWO_14_GADD1,
  GADD2	G2_GGWO_15_GADD2,
  GTEL1	G2_GGWO_16_GTEL1,
  GTEL2	G2_GGWO_17_GTEL2,
  GFAX1	G2_GGWO_18_GFAX1,
  GFAX2	G2_GGWO_19_GFAX2,
  GRAT1	G2_GGWO_20_GRAT1,
  GRAT2	G2_GGWO_21_GRAT2,
  GRAT3	G2_GGWO_22_GRAT3,
  GRAT4	G2_GGWO_23_GRAT4,
  GRAT5	G2_GGWO_24_GRAT5,
  GRAT6	G2_GGWO_25_GRAT6,
  GRAT7	G2_GGWO_26_GRAT7,
  GRAT8	G2_GGWO_27_GRAT8,
  GRAT9	G2_GGWO_28_GRAT9,
  GQUT1	G2_GGWO_29_GQUT1,
  GPPER	G2_GGWO_30_GPPER,
  GBIGO	G2_GGWO_31_GBIGO,
  NAME1	G2_GGWO_32_NAME1,
  NAME2	G2_GGWO_33_NAME2,
  YESNO	G2_GGWO_34_YESNO,
  HTEL1	G2_GGWO_35_GPHON,
  EMAIL	G2_GGWO_36_EMAIL,
  GSSUM	G2_GGWO_37_GSSUM,
  GMEMO	G2_GGWO_38_GMEMO
);

CREATE ASCENDING INDEX G2_GGWO_ ON G2_GGWO (ID);
CREATE ASCENDING INDEX G2_GGWO_HCODE ON G2_GGWO (HCODE);
CREATE ASCENDING INDEX G2_GGWO_GCODE ON G2_GGWO (GCODE);
CREATE ASCENDING INDEX G2_GGWO_GNAME ON G2_GGWO (GNAME);

CREATE GENERATOR G2_GGWO_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER G2_GGWO_ID_TNO FOR G2_GGWO 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(G2_GGWO_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;
