/* Domain definitions */
CREATE DOMAIN SV_GSUM_01_GDATE AS VARCHAR(10);
CREATE DOMAIN SV_GSUM_02_SCODE AS VARCHAR(1);
CREATE DOMAIN SV_GSUM_03_GCODE AS VARCHAR(5);
CREATE DOMAIN SV_GSUM_04_HCODE AS VARCHAR(5);
CREATE DOMAIN SV_GSUM_05_GUBUN AS VARCHAR(2);
CREATE DOMAIN SV_GSUM_06_GSQUT AS DOUBLE PRECISION;
CREATE DOMAIN SV_GSUM_07_GOQUT AS DOUBLE PRECISION;
CREATE DOMAIN SV_GSUM_08_GOSUM AS DOUBLE PRECISION;
CREATE DOMAIN SV_GSUM_09_GJQUT AS DOUBLE PRECISION;
CREATE DOMAIN SV_GSUM_10_GJSUM AS DOUBLE PRECISION;
CREATE DOMAIN SV_GSUM_11_GBQUT AS DOUBLE PRECISION;
CREATE DOMAIN SV_GSUM_12_GBSUM AS DOUBLE PRECISION;
CREATE DOMAIN SV_GSUM_13_GSUSU AS DOUBLE PRECISION;
CREATE DOMAIN SV_GSUM_14_GSSUM AS DOUBLE PRECISION;
CREATE DOMAIN SV_GSUM_15_GMEMO AS TimeStamp;

/* Table: SV_GSUM, Owner: SYSDBA */

CREATE TABLE SV_GSUM 
(
  GDATE	SV_GSUM_01_GDATE,
  SCODE	SV_GSUM_02_SCODE,
  GCODE	SV_GSUM_03_GCODE,
  HCODE	SV_GSUM_04_HCODE,
  GUBUN	SV_GSUM_05_GUBUN,
  GSQUT	SV_GSUM_06_GSQUT,
  GOQUT	SV_GSUM_07_GOQUT,
  GOSUM	SV_GSUM_08_GOSUM,
  GJQUT	SV_GSUM_09_GJQUT,
  GJSUM	SV_GSUM_10_GJSUM,
  GBQUT	SV_GSUM_11_GBQUT,
  GBSUM	SV_GSUM_12_GBSUM,
  GSUSU	SV_GSUM_13_GSUSU,
  GSSUM	SV_GSUM_14_GSSUM,
  GMEMO	SV_GSUM_15_GMEMO
);

CREATE ASCENDING INDEX SV_GSUM_HCODE ON SV_GSUM (HCODE);
CREATE ASCENDING INDEX SV_GSUM_GDATE ON SV_GSUM (GDATE);
CREATE ASCENDING INDEX SV_GSUM_GCODE ON SV_GSUM (GCODE);





/* Domain definitions */
CREATE DOMAIN SV_CSUM_01_GDATE AS VARCHAR(10);
CREATE DOMAIN SV_CSUM_02_SCODE AS VARCHAR(1);
CREATE DOMAIN SV_CSUM_03_GCODE AS VARCHAR(10);
CREATE DOMAIN SV_CSUM_04_HCODE AS VARCHAR(5);
CREATE DOMAIN SV_CSUM_05_GIQUT AS DOUBLE PRECISION;
CREATE DOMAIN SV_CSUM_06_GOQUT AS DOUBLE PRECISION;
CREATE DOMAIN SV_CSUM_07_GJQUT AS DOUBLE PRECISION;
CREATE DOMAIN SV_CSUM_08_GBQUT AS DOUBLE PRECISION;
CREATE DOMAIN SV_CSUM_09_GPQUT AS DOUBLE PRECISION;
CREATE DOMAIN SV_CSUM_10_GSQUT AS DOUBLE PRECISION;
CREATE DOMAIN SV_CSUM_11_GSUSU AS DOUBLE PRECISION;
CREATE DOMAIN SV_CSUM_12_GOSUM AS DOUBLE PRECISION;
CREATE DOMAIN SV_CSUM_13_GBSUM AS DOUBLE PRECISION;
CREATE DOMAIN SV_CSUM_14_GMEMO AS TimeStamp;

/* Table: SV_CSUM, Owner: SYSDBA */

CREATE TABLE SV_CSUM 
(
  GDATE	SV_CSUM_01_GDATE,
  SCODE	SV_CSUM_02_SCODE,
  GCODE	SV_CSUM_03_GCODE,
  HCODE	SV_CSUM_04_HCODE,
  GIQUT	SV_CSUM_05_GIQUT,
  GOQUT	SV_CSUM_06_GOQUT,
  GJQUT	SV_CSUM_07_GJQUT,
  GBQUT	SV_CSUM_08_GBQUT,
  GPQUT	SV_CSUM_09_GPQUT,
  GSQUT	SV_CSUM_10_GSQUT,
  GSUSU	SV_CSUM_11_GSUSU,
  GOSUM	SV_CSUM_12_GOSUM,
  GBSUM	SV_CSUM_13_GBSUM,
  GMEMO	SV_CSUM_14_GMEMO
);

CREATE ASCENDING INDEX SV_CSUM_HCODE ON SV_CSUM (HCODE);
CREATE ASCENDING INDEX SV_CSUM_GDATE ON SV_CSUM (GDATE);
CREATE ASCENDING INDEX SV_CSUM_GCODE ON SV_CSUM (GCODE);





/* Domain definitions */
CREATE DOMAIN SV_CHNG_01_GDATE AS VARCHAR(10);
CREATE DOMAIN SV_CHNG_02_SCODE AS VARCHAR(1);
CREATE DOMAIN SV_CHNG_03_GCODE AS VARCHAR(5);
CREATE DOMAIN SV_CHNG_04_HCODE AS VARCHAR(5);
CREATE DOMAIN SV_CHNG_05_GOQUT AS DOUBLE PRECISION;
CREATE DOMAIN SV_CHNG_06_GOSUM AS DOUBLE PRECISION;
CREATE DOMAIN SV_CHNG_07_GJQUT AS DOUBLE PRECISION;
CREATE DOMAIN SV_CHNG_08_GJSUM AS DOUBLE PRECISION;
CREATE DOMAIN SV_CHNG_09_GBQUT AS DOUBLE PRECISION;
CREATE DOMAIN SV_CHNG_10_GBSUM AS DOUBLE PRECISION;
CREATE DOMAIN SV_CHNG_11_GSUSU AS DOUBLE PRECISION;
CREATE DOMAIN SV_CHNG_12_GSSUM AS DOUBLE PRECISION;
CREATE DOMAIN SV_CHNG_13_GMEMO AS TimeStamp;

/* Table: SV_CHNG, Owner: SYSDBA */

CREATE TABLE SV_CHNG 
(
  GDATE	SV_CHNG_01_GDATE,
  SCODE	SV_CHNG_02_SCODE,
  GCODE	SV_CHNG_03_GCODE,
  HCODE	SV_CHNG_04_HCODE,
  GOQUT	SV_CHNG_05_GOQUT,
  GOSUM	SV_CHNG_06_GOSUM,
  GJQUT	SV_CHNG_07_GJQUT,
  GJSUM	SV_CHNG_08_GJSUM,
  GBQUT	SV_CHNG_09_GBQUT,
  GBSUM	SV_CHNG_10_GBSUM,
  GSUSU	SV_CHNG_11_GSUSU,
  GSSUM	SV_CHNG_12_GSSUM,
  GMEMO	SV_CHNG_13_GMEMO
);

CREATE ASCENDING INDEX SV_CHNG_HCODE ON SV_CHNG (HCODE);
CREATE ASCENDING INDEX SV_CHNG_GDATE ON SV_CHNG (GDATE);
CREATE ASCENDING INDEX SV_CHNG_GCODE ON SV_CHNG (GCODE);





/* Domain definitions */
CREATE DOMAIN SV_GHNG_01_GDATE AS VARCHAR(10);
CREATE DOMAIN SV_GHNG_02_SCODE AS VARCHAR(1);
CREATE DOMAIN SV_GHNG_03_GCODE AS VARCHAR(10);
CREATE DOMAIN SV_GHNG_04_HCODE AS VARCHAR(5);
CREATE DOMAIN SV_GHNG_05_GIQUT AS DOUBLE PRECISION;
CREATE DOMAIN SV_GHNG_06_GOQUT AS DOUBLE PRECISION;
CREATE DOMAIN SV_GHNG_07_GJQUT AS DOUBLE PRECISION;
CREATE DOMAIN SV_GHNG_08_GBQUT AS DOUBLE PRECISION;
CREATE DOMAIN SV_GHNG_09_GPQUT AS DOUBLE PRECISION;
CREATE DOMAIN SV_GHNG_10_GSQUT AS DOUBLE PRECISION;
CREATE DOMAIN SV_GHNG_11_GSUSU AS DOUBLE PRECISION;
CREATE DOMAIN SV_GHNG_12_GOSUM AS DOUBLE PRECISION;
CREATE DOMAIN SV_GHNG_13_GBSUM AS DOUBLE PRECISION;
CREATE DOMAIN SV_GHNG_14_OBQUT AS DOUBLE PRECISION;
CREATE DOMAIN SV_GHNG_15_OBSUM AS DOUBLE PRECISION;
CREATE DOMAIN SV_GHNG_16_GMEMO AS TimeStamp;

/* Table: SV_GHNG, Owner: SYSDBA */

CREATE TABLE SV_GHNG 
(
  GDATE	SV_GHNG_01_GDATE,
  SCODE	SV_GHNG_02_SCODE,
  GCODE	SV_GHNG_03_GCODE,
  HCODE	SV_GHNG_04_HCODE,
  GIQUT	SV_GHNG_05_GIQUT,
  GOQUT	SV_GHNG_06_GOQUT,
  GJQUT	SV_GHNG_07_GJQUT,
  GBQUT	SV_GHNG_08_GBQUT,
  GPQUT	SV_GHNG_09_GPQUT,
  GSQUT	SV_GHNG_10_GSQUT,
  GSUSU	SV_GHNG_11_GSUSU,
  GOSUM	SV_GHNG_12_GOSUM,
  GBSUM	SV_GHNG_13_GBSUM,
  OBQUT	SV_GHNG_14_OBQUT,
  OBSUM	SV_GHNG_15_OBSUM,
  GMEMO	SV_GHNG_16_GMEMO
);

CREATE ASCENDING INDEX SV_GHNG_HCODE ON SV_GHNG (HCODE);
CREATE ASCENDING INDEX SV_GHNG_GDATE ON SV_GHNG (GDATE);
CREATE ASCENDING INDEX SV_GHNG_GCODE ON SV_GHNG (GCODE);
