/* Domain definitions */
CREATE DOMAIN G7_GBUN_00_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN G7_GBUN_01_HCODE AS VARCHAR(5);
CREATE DOMAIN G7_GBUN_02_GCODE AS VARCHAR(5);
CREATE DOMAIN G7_GBUN_03_GNAME AS VARCHAR(20);
CREATE DOMAIN G7_GBUN_04_GMEMO AS TimeStamp;

/* Table: G7_GBUN, Owner: SYSDBA */

CREATE TABLE G7_GBUN 
(
  ID	G7_GBUN_00_ID,
  HCODE	G7_GBUN_01_HCODE,
  GCODE	G7_GBUN_02_GCODE,
  GNAME	G7_GBUN_03_GNAME,
  GMEMO	G7_GBUN_04_GMEMO
);

CREATE ASCENDING INDEX G7_GBUN_ ON G7_GBUN (ID);
CREATE ASCENDING INDEX G7_GBUN_HCODE ON G7_GBUN (HCODE);
CREATE ASCENDING INDEX G7_GBUN_GCODE ON G7_GBUN (GCODE);

CREATE GENERATOR G7_GBUN_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER G7_GBUN_ID_TNO FOR G7_GBUN 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(G7_GBUN_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;





/* Domain definitions */
CREATE DOMAIN G7_GGEO_00_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN G7_GGEO_01_HCODE AS VARCHAR(5);
CREATE DOMAIN G7_GGEO_02_GUBUN AS VARCHAR(5);
CREATE DOMAIN G7_GGEO_03_JUBUN AS VARCHAR(6);
CREATE DOMAIN G7_GGEO_04_SCODE AS VARCHAR(1);
CREATE DOMAIN G7_GGEO_05_GCODE AS VARCHAR(5);
CREATE DOMAIN G7_GGEO_06_OCODE AS VARCHAR(5);
CREATE DOMAIN G7_GGEO_07_GNAME AS VARCHAR(24);
CREATE DOMAIN G7_GGEO_08_GPOSA AS VARCHAR(20);
CREATE DOMAIN G7_GGEO_09_GNUMB AS VARCHAR(12);
CREATE DOMAIN G7_GGEO_10_GUPER AS VARCHAR(20);
CREATE DOMAIN G7_GGEO_11_GJOMO AS VARCHAR(20);
CREATE DOMAIN G7_GGEO_12_NAME1 AS VARCHAR(30);
CREATE DOMAIN G7_GGEO_13_NAME2 AS VARCHAR(30);
CREATE DOMAIN G7_GGEO_14_JUMIN AS VARCHAR(14);
CREATE DOMAIN G7_GGEO_15_GPPER AS VARCHAR(10);
CREATE DOMAIN G7_GGEO_16_GPOST AS VARCHAR(7);
CREATE DOMAIN G7_GGEO_17_GADD1 AS VARCHAR(44);
CREATE DOMAIN G7_GGEO_18_GADD2 AS VARCHAR(44);
CREATE DOMAIN G7_GGEO_19_GTEL1 AS VARCHAR(4);
CREATE DOMAIN G7_GGEO_20_GTEL2 AS VARCHAR(20);
CREATE DOMAIN G7_GGEO_21_GFAX1 AS VARCHAR(4);
CREATE DOMAIN G7_GGEO_22_GFAX2 AS VARCHAR(20);
CREATE DOMAIN G7_GGEO_23_EMAIL AS VARCHAR(40);
CREATE DOMAIN G7_GGEO_24_GBIGO AS VARCHAR(40);
CREATE DOMAIN G7_GGEO_25_GIQUT AS DOUBLE PRECISION
	  DEFAULT 0;
CREATE DOMAIN G7_GGEO_26_GISUM AS DOUBLE PRECISION
	  DEFAULT 0;
CREATE DOMAIN G7_GGEO_27_GOSUM AS DOUBLE PRECISION
	  DEFAULT 0;
CREATE DOMAIN G7_GGEO_28_GSSUM AS DOUBLE PRECISION
	  DEFAULT 0;
CREATE DOMAIN G7_GGEO_29_GDATE AS VARCHAR(10);
CREATE DOMAIN G7_GGEO_30_GMEMO AS TimeStamp;

/* Table: G7_GGEO, Owner: SYSDBA */

CREATE TABLE G7_GGEO 
(
  ID	G7_GGEO_00_ID,
  HCODE	G7_GGEO_01_HCODE,
  GUBUN	G7_GGEO_02_GUBUN,
  JUBUN	G7_GGEO_03_JUBUN,
  SCODE	G7_GGEO_04_SCODE,
  GCODE	G7_GGEO_05_GCODE,
  OCODE	G7_GGEO_06_OCODE,
  GNAME	G7_GGEO_07_GNAME,
  GPOSA	G7_GGEO_08_GPOSA,
  GNUMB	G7_GGEO_09_GNUMB,
  GUPER	G7_GGEO_10_GUPER,
  GJOMO	G7_GGEO_11_GJOMO,
  NAME1	G7_GGEO_12_NAME1,
  NAME2	G7_GGEO_13_NAME2,
  JUMIN	G7_GGEO_14_JUMIN,
  GPPER	G7_GGEO_15_GPPER,
  GPOST	G7_GGEO_16_GPOST,
  GADD1	G7_GGEO_17_GADD1,
  GADD2	G7_GGEO_18_GADD2,
  GTEL1	G7_GGEO_19_GTEL1,
  GTEL2	G7_GGEO_20_GTEL2,
  GFAX1	G7_GGEO_21_GFAX1,
  GFAX2	G7_GGEO_22_GFAX2,
  EMAIL	G7_GGEO_23_EMAIL,
  GBIGO	G7_GGEO_24_GBIGO,
  GIQUT	G7_GGEO_25_GIQUT,
  GISUM	G7_GGEO_26_GISUM,
  GOSUM	G7_GGEO_27_GOSUM,
  GSSUM	G7_GGEO_28_GSSUM,
  GDATE	G7_GGEO_29_GDATE,
  GMEMO	G7_GGEO_30_GMEMO
);

CREATE ASCENDING INDEX G7_GGEO_ ON G7_GGEO (ID);
CREATE ASCENDING INDEX G7_GGEO_HCODE ON G7_GGEO (HCODE);
CREATE ASCENDING INDEX G7_GGEO_GCODE ON G7_GGEO (GCODE);
CREATE ASCENDING INDEX G7_GGEO_GNAME ON G7_GGEO (GNAME);

CREATE GENERATOR G7_GGEO_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER G7_GGEO_ID_TNO FOR G7_GGEO 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(G7_GGEO_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;
