/* Domain definitions */
CREATE DOMAIN G8_GBUN_00_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN G8_GBUN_01_HCODE AS VARCHAR(5);
CREATE DOMAIN G8_GBUN_02_GCODE AS VARCHAR(5);
CREATE DOMAIN G8_GBUN_03_GNAME AS VARCHAR(20);
CREATE DOMAIN G8_GBUN_04_GMEMO AS TimeStamp;

/* Table: G8_GBUN, Owner: SYSDBA */

CREATE TABLE G8_GBUN 
(
  ID	G8_GBUN_00_ID,
  HCODE	G8_GBUN_01_HCODE,
  GCODE	G8_GBUN_02_GCODE,
  GNAME	G8_GBUN_03_GNAME,
  GMEMO	G8_GBUN_04_GMEMO
);

CREATE ASCENDING INDEX G8_GBUN_ ON G8_GBUN (ID);
CREATE ASCENDING INDEX G8_GBUN_HCODE ON G8_GBUN (HCODE);
CREATE ASCENDING INDEX G8_GBUN_GCODE ON G8_GBUN (GCODE);

CREATE GENERATOR G8_GBUN_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER G8_GBUN_ID_TNO FOR G8_GBUN 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(G8_GBUN_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;





/* Domain definitions */
CREATE DOMAIN G8_GGEO_00_ID AS DOUBLE PRECISION
	 DEFAULT 0 NOT NULL;
CREATE DOMAIN G8_GGEO_01_HCODE AS VARCHAR(5);
CREATE DOMAIN G8_GGEO_02_GUBUN AS VARCHAR(5);
CREATE DOMAIN G8_GGEO_03_JUBUN AS VARCHAR(6);
CREATE DOMAIN G8_GGEO_04_SCODE AS VARCHAR(1);
CREATE DOMAIN G8_GGEO_05_GCODE AS VARCHAR(5);
CREATE DOMAIN G8_GGEO_06_OCODE AS VARCHAR(5);
CREATE DOMAIN G8_GGEO_07_GNAME AS VARCHAR(24);
CREATE DOMAIN G8_GGEO_08_GPOSA AS VARCHAR(30);
CREATE DOMAIN G8_GGEO_09_GDATE AS VARCHAR(10);
CREATE DOMAIN G8_GGEO_10_NAME1 AS VARCHAR(30);
CREATE DOMAIN G8_GGEO_11_NAME2 AS VARCHAR(30);
CREATE DOMAIN G8_GGEO_12_GPOST AS VARCHAR(7);
CREATE DOMAIN G8_GGEO_13_GADD1 AS VARCHAR(44);
CREATE DOMAIN G8_GGEO_14_GADD2 AS VARCHAR(44);
CREATE DOMAIN G8_GGEO_15_GTEL1 AS VARCHAR(4);
CREATE DOMAIN G8_GGEO_16_GTEL2 AS VARCHAR(14);
CREATE DOMAIN G8_GGEO_17_GFAX1 AS VARCHAR(4);
CREATE DOMAIN G8_GGEO_18_GFAX2 AS VARCHAR(14);
CREATE DOMAIN G8_GGEO_19_EMAIL AS VARCHAR(40);
CREATE DOMAIN G8_GGEO_20_GBIGO AS VARCHAR(40);
CREATE DOMAIN G8_GGEO_21_GMEMO AS TimeStamp;

/* Table: G8_GGEO, Owner: SYSDBA */

CREATE TABLE G8_GGEO 
(
  ID	G8_GGEO_00_ID,
  HCODE	G8_GGEO_01_HCODE,
  GUBUN	G8_GGEO_02_GUBUN,
  JUBUN	G8_GGEO_03_JUBUN,
  SCODE	G8_GGEO_04_SCODE,
  GCODE	G8_GGEO_05_GCODE,
  OCODE	G8_GGEO_06_OCODE,
  GNAME	G8_GGEO_07_GNAME,
  GPOSA	G8_GGEO_08_GPOSA,
  GDATE	G8_GGEO_09_GDATE,
  NAME1	G8_GGEO_10_NAME1,
  NAME2	G8_GGEO_11_NAME2,
  GPOST	G8_GGEO_12_GPOST,
  GADD1	G8_GGEO_13_GADD1,
  GADD2	G8_GGEO_14_GADD2,
  GTEL1	G8_GGEO_15_GTEL1,
  GTEL2	G8_GGEO_16_GTEL2,
  GFAX1	G8_GGEO_17_GFAX1,
  GFAX2	G8_GGEO_18_GFAX2,
  EMAIL	G8_GGEO_19_EMAIL,
  GBIGO	G8_GGEO_20_GBIGO,
  GMEMO	G8_GGEO_21_GMEMO
);

CREATE ASCENDING INDEX G8_GGEO_ ON G8_GGEO (ID);
CREATE ASCENDING INDEX G8_GGEO_HCODE ON G8_GGEO (HCODE);
CREATE ASCENDING INDEX G8_GGEO_GCODE ON G8_GGEO (GCODE);
CREATE ASCENDING INDEX G8_GGEO_GNAME ON G8_GGEO (GNAME);

CREATE GENERATOR G8_GGEO_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER G8_GGEO_ID_TNO FOR G8_GGEO 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(G8_GGEO_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;
