/* Domain definitions */
CREATE DOMAIN IN_GSUM_01_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN IN_GSUM_02_GDATE AS VARCHAR(10);
CREATE DOMAIN IN_GSUM_03_SCODE AS VARCHAR(1);
CREATE DOMAIN IN_GSUM_04_GCODE AS VARCHAR(5);
CREATE DOMAIN IN_GSUM_05_HCODE AS VARCHAR(5);
CREATE DOMAIN IN_GSUM_06_GSSUM AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN IN_GSUM_07_GMEMO AS TimeStamp;

/* Table: IN_GSUM, Owner: SYSDBA */

CREATE TABLE IN_GSUM 
(
  ID	IN_GSUM_01_ID,
  GDATE	IN_GSUM_02_GDATE,
  SCODE	IN_GSUM_03_SCODE,
  GCODE	IN_GSUM_04_GCODE,
  HCODE	IN_GSUM_05_HCODE,
  GSSUM	IN_GSUM_06_GSSUM,
  GMEMO	IN_GSUM_07_GMEMO
);


CREATE ASCENDING INDEX IN_GSUM_ ON IN_GSUM (ID);
CREATE ASCENDING INDEX IN_GSUM_HCODE ON IN_GSUM (HCODE);
CREATE ASCENDING INDEX IN_GSUM_GCODE ON IN_GSUM (GCODE);

CREATE GENERATOR IN_GSUM_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER IN_GSUM_ID_TNO FOR IN_GSUM 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(IN_GSUM_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;





/* Domain definitions */
CREATE DOMAIN IN_CSUM_01_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN IN_CSUM_02_GDATE AS VARCHAR(10);
CREATE DOMAIN IN_CSUM_03_SCODE AS VARCHAR(1);
CREATE DOMAIN IN_CSUM_04_GCODE AS VARCHAR(10);
CREATE DOMAIN IN_CSUM_05_HCODE AS VARCHAR(5);
CREATE DOMAIN IN_CSUM_06_GSSUM AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN IN_CSUM_07_GMEMO AS TimeStamp;

/* Table: IN_CSUM, Owner: SYSDBA */

CREATE TABLE IN_CSUM 
(
  ID	IN_CSUM_01_ID,
  GDATE	IN_CSUM_02_GDATE,
  SCODE	IN_CSUM_03_SCODE,
  GCODE	IN_CSUM_04_GCODE,
  HCODE	IN_CSUM_05_HCODE,
  GSSUM	IN_CSUM_06_GSSUM,
  GMEMO	IN_CSUM_07_GMEMO
);


CREATE ASCENDING INDEX IN_CSUM_ ON IN_CSUM (ID);
CREATE ASCENDING INDEX IN_CSUM_HCODE ON IN_CSUM (HCODE);
CREATE ASCENDING INDEX IN_CSUM_GCODE ON IN_CSUM (GCODE);

CREATE GENERATOR IN_CSUM_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER IN_CSUM_ID_TNO FOR IN_CSUM 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(IN_CSUM_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;





/* Domain definitions */
CREATE DOMAIN SG_GSUM_01_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN SG_GSUM_02_GDATE AS VARCHAR(10);
CREATE DOMAIN SG_GSUM_03_SCODE AS VARCHAR(1);
CREATE DOMAIN SG_GSUM_04_GCODE AS VARCHAR(5);
CREATE DOMAIN SG_GSUM_05_HCODE AS VARCHAR(5);
CREATE DOMAIN SG_GSUM_06_GSSUM AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN SG_GSUM_07_GOSUM AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN SG_GSUM_08_GBSUM AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN SG_GSUM_09_GBIGO AS VARCHAR(20);
CREATE DOMAIN SG_GSUM_10_GMEMO AS TimeStamp;

/* Table: SG_GSUM, Owner: SYSDBA */

CREATE TABLE SG_GSUM 
(
  ID	SG_GSUM_01_ID,
  GDATE	SG_GSUM_02_GDATE,
  SCODE	SG_GSUM_03_SCODE,
  GCODE	SG_GSUM_04_GCODE,
  HCODE	SG_GSUM_05_HCODE,
  GSSUM	SG_GSUM_06_GSSUM,
  GOSUM	SG_GSUM_07_GOSUM,
  GBSUM	SG_GSUM_08_GBSUM,
  GBIGO	SG_GSUM_09_GBIGO,
  GMEMO	SG_GSUM_10_GMEMO
);


CREATE ASCENDING INDEX SG_GSUM_ ON SG_GSUM (ID);
CREATE ASCENDING INDEX SG_GSUM_HCODE ON SG_GSUM (HCODE);
CREATE ASCENDING INDEX SG_GSUM_GDATE ON SG_GSUM (GDATE);
CREATE ASCENDING INDEX SG_GSUM_GCODE ON SG_GSUM (GCODE);

CREATE GENERATOR SG_GSUM_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER SG_GSUM_ID_TNO FOR SG_GSUM 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(SG_GSUM_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;





/* Domain definitions */
CREATE DOMAIN SG_CSUM_01_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN SG_CSUM_02_GDATE AS VARCHAR(10);
CREATE DOMAIN SG_CSUM_03_SCODE AS VARCHAR(1);
CREATE DOMAIN SG_CSUM_04_GCODE AS VARCHAR(10);
CREATE DOMAIN SG_CSUM_05_HCODE AS VARCHAR(5);
CREATE DOMAIN SG_CSUM_06_GSSUM AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN SG_CSUM_07_GOSUM AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN SG_CSUM_08_GBSUM AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN SG_CSUM_09_GBIGO AS VARCHAR(20);
CREATE DOMAIN SG_CSUM_10_GMEMO AS TimeStamp;

/* Table: SG_CSUM, Owner: SYSDBA */

CREATE TABLE SG_CSUM 
(
  ID	SG_CSUM_01_ID,
  GDATE	SG_CSUM_02_GDATE,
  SCODE	SG_CSUM_03_SCODE,
  GCODE	SG_CSUM_04_GCODE,
  HCODE	SG_CSUM_05_HCODE,
  GSSUM	SG_CSUM_06_GSSUM,
  GOSUM	SG_CSUM_07_GOSUM,
  GBSUM	SG_CSUM_08_GBSUM,
  GBIGO	SG_CSUM_09_GBIGO,
  GMEMO	SG_CSUM_10_GMEMO
);


CREATE ASCENDING INDEX SG_CSUM_ ON SG_CSUM (ID);
CREATE ASCENDING INDEX SG_CSUM_HCODE ON SG_CSUM (HCODE);
CREATE ASCENDING INDEX SG_CSUM_GDATE ON SG_CSUM (GDATE);
CREATE ASCENDING INDEX SG_CSUM_GCODE ON SG_CSUM (GCODE);

CREATE GENERATOR SG_CSUM_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER SG_CSUM_ID_TNO FOR SG_CSUM 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(SG_CSUM_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;





/* Domain definitions */
CREATE DOMAIN GS_GSUM_01_GDATE AS VARCHAR(7);
CREATE DOMAIN GS_GSUM_02_SCODE AS VARCHAR(1);
CREATE DOMAIN GS_GSUM_03_GCODE AS VARCHAR(5);
CREATE DOMAIN GS_GSUM_04_HCODE AS VARCHAR(5);
CREATE DOMAIN GS_GSUM_05_GOQUT AS DOUBLE PRECISION;
CREATE DOMAIN GS_GSUM_06_GOSUM AS DOUBLE PRECISION;
CREATE DOMAIN GS_GSUM_07_GJQUT AS DOUBLE PRECISION;
CREATE DOMAIN GS_GSUM_08_GJSUM AS DOUBLE PRECISION;
CREATE DOMAIN GS_GSUM_09_GBQUT AS DOUBLE PRECISION;
CREATE DOMAIN GS_GSUM_10_GBSUM AS DOUBLE PRECISION;
CREATE DOMAIN GS_GSUM_11_GSUSU AS DOUBLE PRECISION;
CREATE DOMAIN GS_GSUM_12_GSUMX AS DOUBLE PRECISION;
CREATE DOMAIN GS_GSUM_13_GSUMY AS DOUBLE PRECISION;
CREATE DOMAIN GS_GSUM_14_GMEMO AS TimeStamp;

/* Table: GS_GSUM, Owner: SYSDBA */

CREATE TABLE GS_GSUM 
(
  GDATE	GS_GSUM_01_GDATE,
  SCODE	GS_GSUM_02_SCODE,
  GCODE	GS_GSUM_03_GCODE,
  HCODE	GS_GSUM_04_HCODE,
  GOQUT	GS_GSUM_05_GOQUT,
  GOSUM	GS_GSUM_06_GOSUM,
  GJQUT	GS_GSUM_07_GJQUT,
  GJSUM	GS_GSUM_08_GJSUM,
  GBQUT	GS_GSUM_09_GBQUT,
  GBSUM	GS_GSUM_10_GBSUM,
  GSUSU	GS_GSUM_11_GSUSU,
  GSUMX	GS_GSUM_12_GSUMX,
  GSUMY	GS_GSUM_13_GSUMY,
  GMEMO	GS_GSUM_14_GMEMO
);

CREATE ASCENDING INDEX GS_GSUM_HCODE ON GS_GSUM (HCODE);
CREATE ASCENDING INDEX GS_GSUM_GDATE ON GS_GSUM (GDATE);
CREATE ASCENDING INDEX GS_GSUM_GCODE ON GS_GSUM (GCODE);





/* Domain definitions */
CREATE DOMAIN GS_CSUM_01_GDATE AS VARCHAR(7);
CREATE DOMAIN GS_CSUM_02_SCODE AS VARCHAR(1);
CREATE DOMAIN GS_CSUM_03_GCODE AS VARCHAR(10);
CREATE DOMAIN GS_CSUM_04_HCODE AS VARCHAR(5);
CREATE DOMAIN GS_CSUM_05_GIQUT AS DOUBLE PRECISION;
CREATE DOMAIN GS_CSUM_06_GOQUT AS DOUBLE PRECISION;
CREATE DOMAIN GS_CSUM_07_GJQUT AS DOUBLE PRECISION;
CREATE DOMAIN GS_CSUM_08_GBQUT AS DOUBLE PRECISION;
CREATE DOMAIN GS_CSUM_09_GPQUT AS DOUBLE PRECISION;
CREATE DOMAIN GS_CSUM_10_GOSUM AS DOUBLE PRECISION;
CREATE DOMAIN GS_CSUM_11_GBSUM AS DOUBLE PRECISION;
CREATE DOMAIN GS_CSUM_12_GSUMX AS DOUBLE PRECISION;
CREATE DOMAIN GS_CSUM_13_GSUMY AS DOUBLE PRECISION;
CREATE DOMAIN GS_CSUM_14_GMEMO AS TimeStamp;

/* Table: GS_CSUM, Owner: SYSDBA */

CREATE TABLE GS_CSUM 
(
  GDATE	GS_CSUM_01_GDATE,
  SCODE	GS_CSUM_02_SCODE,
  GCODE	GS_CSUM_03_GCODE,
  HCODE	GS_CSUM_04_HCODE,
  GIQUT	GS_CSUM_05_GIQUT,
  GOQUT	GS_CSUM_06_GOQUT,
  GJQUT	GS_CSUM_07_GJQUT,
  GBQUT	GS_CSUM_08_GBQUT,
  GPQUT	GS_CSUM_09_GPQUT,
  GOSUM	GS_CSUM_10_GOSUM,
  GBSUM	GS_CSUM_11_GBSUM,
  GSUMX	GS_CSUM_12_GSUMX,
  GSUMY	GS_CSUM_13_GSUMY,
  GMEMO	GS_CSUM_14_GMEMO
);

CREATE ASCENDING INDEX GS_CSUM_HCODE ON GS_CSUM (HCODE);
CREATE ASCENDING INDEX GS_CSUM_GDATE ON GS_CSUM (GDATE);
CREATE ASCENDING INDEX GS_CSUM_GCODE ON GS_CSUM (GCODE);
