/* Domain definitions */
CREATE DOMAIN G0_GBUN_00_ID AS DOUBLE PRECISION
	 DEFAULT 0 NOT NULL;
CREATE DOMAIN G0_GBUN_01_HCODE AS VARCHAR(5);
CREATE DOMAIN G0_GBUN_02_GCODE AS VARCHAR(5);
CREATE DOMAIN G0_GBUN_03_GNAME AS VARCHAR(20);
CREATE DOMAIN G0_GBUN_04_GMEMO AS TimeStamp;

/* Table: G0_GBUN, Owner: SYSDBA */

CREATE TABLE G0_GBUN 
(
  ID	G0_GBUN_00_ID,
  HCODE	G0_GBUN_01_HCODE,
  GCODE	G0_GBUN_02_GCODE,
  GNAME	G0_GBUN_03_GNAME,
  GMEMO	G0_GBUN_04_GMEMO
);





/* Domain definitions */
CREATE DOMAIN G1_GBUN_00_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN G1_GBUN_01_HCODE AS VARCHAR(5);
CREATE DOMAIN G1_GBUN_02_GCODE AS VARCHAR(5);
CREATE DOMAIN G1_GBUN_03_GNAME AS VARCHAR(20);
CREATE DOMAIN G1_GBUN_04_GMEMO AS TimeStamp;

/* Table: G1_GBUN, Owner: SYSDBA */

CREATE TABLE G1_GBUN 
(
  ID	G1_GBUN_00_ID,
  HCODE	G1_GBUN_01_HCODE,
  GCODE	G1_GBUN_02_GCODE,
  GNAME	G1_GBUN_03_GNAME,
  GMEMO	G1_GBUN_04_GMEMO
);

CREATE ASCENDING INDEX G1_GBUN_ ON G1_GBUN (ID);
CREATE ASCENDING INDEX G1_GBUN_HCODE ON G1_GBUN (HCODE);
CREATE ASCENDING INDEX G1_GBUN_GCODE ON G1_GBUN (GCODE);

CREATE GENERATOR G1_GBUN_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER G1_GBUN_ID_TNO FOR G1_GBUN 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(G1_GBUN_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;





/* Domain definitions */
CREATE DOMAIN G1_GGEO_00_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN G1_GGEO_01_HCODE AS VARCHAR(5);
CREATE DOMAIN G1_GGEO_02_GUBUN AS VARCHAR(5);
CREATE DOMAIN G1_GGEO_03_JUBUN AS VARCHAR(6);
CREATE DOMAIN G1_GGEO_04_PUBUN AS VARCHAR(2);
CREATE DOMAIN G1_GGEO_05_SCODE AS VARCHAR(1);
CREATE DOMAIN G1_GGEO_06_GCODE AS VARCHAR(5);
CREATE DOMAIN G1_GGEO_07_OCODE AS VARCHAR(5);
CREATE DOMAIN G1_GGEO_08_GNAME AS VARCHAR(24);
CREATE DOMAIN G1_GGEO_09_GPOSA AS VARCHAR(20);
CREATE DOMAIN G1_GGEO_10_GNUMB AS VARCHAR(12);
CREATE DOMAIN G1_GGEO_11_GUPER AS VARCHAR(20);
CREATE DOMAIN G1_GGEO_12_GJOMO AS VARCHAR(20);
CREATE DOMAIN G1_GGEO_13_GPOST AS VARCHAR(7);
CREATE DOMAIN G1_GGEO_14_GADD1 AS VARCHAR(44);
CREATE DOMAIN G1_GGEO_15_GADD2 AS VARCHAR(44);
CREATE DOMAIN G1_GGEO_16_GTEL1 AS VARCHAR(4);
CREATE DOMAIN G1_GGEO_17_GTEL2 AS VARCHAR(20);
CREATE DOMAIN G1_GGEO_18_GFAX1 AS VARCHAR(4);
CREATE DOMAIN G1_GGEO_19_GFAX2 AS VARCHAR(20);
CREATE DOMAIN G1_GGEO_20_GRAT1 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G1_GGEO_21_GRAT2 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G1_GGEO_22_GRAT3 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G1_GGEO_23_GRAT4 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G1_GGEO_24_GRAT5 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G1_GGEO_25_GRAT6 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G1_GGEO_26_GRAT7 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G1_GGEO_27_GRAT8 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G1_GGEO_28_GRAT9 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G1_GGEO_29_GQUT1 AS DOUBLE PRECISION
	  DEFAULT 0;
CREATE DOMAIN G1_GGEO_30_GPPER AS VARCHAR(10);
CREATE DOMAIN G1_GGEO_31_GBIGO AS VARCHAR(40);
CREATE DOMAIN G1_GGEO_32_NAME1 AS VARCHAR(40);
CREATE DOMAIN G1_GGEO_33_NAME2 AS VARCHAR(40);
CREATE DOMAIN G1_GGEO_34_YESNO AS VARCHAR(5);
CREATE DOMAIN G1_GGEO_35_GPHON AS VARCHAR(15);
CREATE DOMAIN G1_GGEO_36_EMAIL AS VARCHAR(15);
CREATE DOMAIN G1_GGEO_37_GSSUM AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN G1_GGEO_38_GMEMO AS TimeStamp;

/* Table: G1_GGEO, Owner: SYSDBA */

CREATE TABLE G1_GGEO 
(
  ID	G1_GGEO_00_ID,
  HCODE	G1_GGEO_01_HCODE,
  GUBUN	G1_GGEO_02_GUBUN,
  JUBUN	G1_GGEO_03_JUBUN,
  PUBUN	G1_GGEO_04_PUBUN,
  SCODE	G1_GGEO_05_SCODE,
  GCODE	G1_GGEO_06_GCODE,
  OCODE	G1_GGEO_07_OCODE,
  GNAME	G1_GGEO_08_GNAME,
  GPOSA	G1_GGEO_09_GPOSA,
  GNUMB	G1_GGEO_10_GNUMB,
  GUPER	G1_GGEO_11_GUPER,
  GJOMO	G1_GGEO_12_GJOMO,
  GPOST	G1_GGEO_13_GPOST,
  GADD1	G1_GGEO_14_GADD1,
  GADD2	G1_GGEO_15_GADD2,
  GTEL1	G1_GGEO_16_GTEL1,
  GTEL2	G1_GGEO_17_GTEL2,
  GFAX1	G1_GGEO_18_GFAX1,
  GFAX2	G1_GGEO_19_GFAX2,
  GRAT1	G1_GGEO_20_GRAT1,
  GRAT2	G1_GGEO_21_GRAT2,
  GRAT3	G1_GGEO_22_GRAT3,
  GRAT4	G1_GGEO_23_GRAT4,
  GRAT5	G1_GGEO_24_GRAT5,
  GRAT6	G1_GGEO_25_GRAT6,
  GRAT7	G1_GGEO_26_GRAT7,
  GRAT8	G1_GGEO_27_GRAT8,
  GRAT9	G1_GGEO_28_GRAT9,
  GQUT1	G1_GGEO_29_GQUT1,
  GPPER	G1_GGEO_30_GPPER,
  GBIGO	G1_GGEO_31_GBIGO,
  NAME1	G1_GGEO_32_NAME1,
  NAME2	G1_GGEO_33_NAME2,
  YESNO	G1_GGEO_34_YESNO,
  HTEL1	G1_GGEO_35_GPHON,
  EMAIL	G1_GGEO_36_EMAIL,
  GSSUM	G1_GGEO_37_GSSUM,
  GMEMO	G1_GGEO_38_GMEMO
);

CREATE ASCENDING INDEX G1_GGEO_ ON G1_GGEO (ID);
CREATE ASCENDING INDEX G1_GGEO_HCODE ON G1_GGEO (HCODE);
CREATE ASCENDING INDEX G1_GGEO_GCODE ON G1_GGEO (GCODE);
CREATE ASCENDING INDEX G1_GGEO_GNAME ON G1_GGEO (GNAME);

CREATE GENERATOR G1_GGEO_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER G1_GGEO_ID_TNO FOR G1_GGEO 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(G1_GGEO_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;
