/* Domain definitions */
CREATE DOMAIN T1_GBUN_01_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN T1_GBUN_02_HCODE AS VARCHAR(5);
CREATE DOMAIN T1_GBUN_03_GCODE AS VARCHAR(5);
CREATE DOMAIN T1_GBUN_04_GNAME AS VARCHAR(20);
CREATE DOMAIN T1_GBUN_05_GJISA AS VARCHAR(15);
CREATE DOMAIN T1_GBUN_06_JUBUN AS VARCHAR(15);
CREATE DOMAIN T1_GBUN_07_BEBON AS VARCHAR(10);
CREATE DOMAIN T1_GBUN_08_GMEMO AS TimeStamp;

/* Table: T1_GBUN, Owner: SYSDBA */

CREATE TABLE T1_GBUN 
(
  ID	T1_GBUN_01_ID,
  HCODE	T1_GBUN_02_HCODE,
  GCODE	T1_GBUN_03_GCODE,
  GNAME	T1_GBUN_04_GNAME,
  GJISA	T1_GBUN_05_GJISA,
  JUBUN	T1_GBUN_06_JUBUN,
  BEBON	T1_GBUN_07_BEBON,
  GMEMO	T1_GBUN_08_GMEMO
);


CREATE ASCENDING INDEX T1_GBUN_ ON T1_GBUN (ID);
CREATE ASCENDING INDEX T1_GBUN_HCODE ON T1_GBUN (HCODE);
CREATE ASCENDING INDEX T1_GBUN_GCODE ON T1_GBUN (GCODE);

CREATE GENERATOR T1_GBUN_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER T1_GBUN_ID_TNO FOR T1_GBUN 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(T1_GBUN_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;





/* Domain definitions */
CREATE DOMAIN T1_SSUB_01_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN T1_SSUB_02_HCODE AS VARCHAR(5);
CREATE DOMAIN T1_SSUB_03_GDATE AS VARCHAR(10);
CREATE DOMAIN T1_SSUB_04_GCODE AS VARCHAR(5);
CREATE DOMAIN T1_SSUB_05_GNAME AS VARCHAR(24);
CREATE DOMAIN T1_SSUB_06_NAME1 AS VARCHAR(30);
CREATE DOMAIN T1_SSUB_07_NAME2 AS VARCHAR(30);
CREATE DOMAIN T1_SSUB_08_GNUMB AS VARCHAR(30);
CREATE DOMAIN T1_SSUB_09_GBIGO AS VARCHAR(50);
CREATE DOMAIN T1_SSUB_10_GSSUM AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T1_SSUB_11_GMEMO AS TimeStamp;

/* Table: T1_SSUB, Owner: SYSDBA */

CREATE TABLE T1_SSUB 
(
  ID	T1_SSUB_01_ID,
  HCODE	T1_SSUB_02_HCODE,
  GDATE	T1_SSUB_03_GDATE,
  GCODE	T1_SSUB_04_GCODE,
  GNAME	T1_SSUB_05_GNAME,
  NAME1	T1_SSUB_06_NAME1,
  NAME2	T1_SSUB_07_NAME2,
  GNUMB	T1_SSUB_08_GNUMB,
  GBIGO	T1_SSUB_09_GBIGO,
  GSSUM	T1_SSUB_10_GSSUM,
  GMEMO	T1_SSUB_11_GMEMO
);


CREATE ASCENDING INDEX T1_SSUB_ ON T1_SSUB (ID);
CREATE ASCENDING INDEX T1_SSUB_HCODE ON T1_SSUB (HCODE);
CREATE ASCENDING INDEX T1_SSUB_GDATE ON T1_SSUB (GDATE);
CREATE ASCENDING INDEX T1_SSUB_GCODE ON T1_SSUB (GCODE);

CREATE GENERATOR T1_SSUB_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER T1_SSUB_ID_TNO FOR T1_SSUB 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(T1_SSUB_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;





/* Domain definitions */
CREATE DOMAIN T2_SSUB_01_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN T2_SSUB_02_HCODE AS VARCHAR(5);
CREATE DOMAIN T2_SSUB_03_GDATE AS VARCHAR(10);
CREATE DOMAIN T2_SSUB_04_BIGO1 AS VARCHAR(5);
CREATE DOMAIN T2_SSUB_05_BIGO2 AS VARCHAR(24);
CREATE DOMAIN T2_SSUB_06_YESNO AS VARCHAR(30);
CREATE DOMAIN T2_SSUB_07_SUM01 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM02 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM03 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM04 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM05 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM06 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM07 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM08 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM09 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM10 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM11 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM12 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM13 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM14 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM15 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM16 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM17 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM18 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM19 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM20 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM21 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM22 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM23 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM24 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM25 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM26 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM27 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM28 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM29 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM30 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM31 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM32 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM33 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM34 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM35 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM36 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_07_SUM37 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T2_SSUB_08_GMEMO AS TimeStamp;

/* Table: T2_SSUB, Owner: SYSDBA */

CREATE TABLE T2_SSUB 
(
  ID	T2_SSUB_01_ID,
  HCODE	T2_SSUB_02_HCODE,
  GDATE	T2_SSUB_03_GDATE,
  BIGO1	T2_SSUB_04_BIGO1,
  BIGO2	T2_SSUB_05_BIGO2,
  YESNO	T2_SSUB_06_YESNO,
  SUM01	T2_SSUB_07_SUM01,
  SUM02	T2_SSUB_07_SUM02,
  SUM03	T2_SSUB_07_SUM03,
  SUM04	T2_SSUB_07_SUM04,
  SUM05	T2_SSUB_07_SUM05,
  SUM06	T2_SSUB_07_SUM06,
  SUM07	T2_SSUB_07_SUM07,
  SUM08	T2_SSUB_07_SUM08,
  SUM09	T2_SSUB_07_SUM09,
  SUM10	T2_SSUB_07_SUM10,
  SUM11	T2_SSUB_07_SUM11,
  SUM12	T2_SSUB_07_SUM12,
  SUM13	T2_SSUB_07_SUM13,
  SUM14	T2_SSUB_07_SUM14,
  SUM15	T2_SSUB_07_SUM15,
  SUM16	T2_SSUB_07_SUM16,
  SUM17	T2_SSUB_07_SUM17,
  SUM18	T2_SSUB_07_SUM18,
  SUM19	T2_SSUB_07_SUM19,
  SUM20	T2_SSUB_07_SUM20,
  SUM21	T2_SSUB_07_SUM21,
  SUM22	T2_SSUB_07_SUM22,
  SUM23	T2_SSUB_07_SUM23,
  SUM24	T2_SSUB_07_SUM24,
  SUM25	T2_SSUB_07_SUM25,
  SUM26	T2_SSUB_07_SUM26,
  SUM27	T2_SSUB_07_SUM27,
  SUM28	T2_SSUB_07_SUM28,
  SUM29	T2_SSUB_07_SUM29,
  SUM30	T2_SSUB_07_SUM30,
  SUM31	T2_SSUB_07_SUM31,
  SUM32	T2_SSUB_07_SUM32,
  SUM33	T2_SSUB_07_SUM33,
  SUM34	T2_SSUB_07_SUM34,
  SUM35	T2_SSUB_07_SUM35,
  SUM36	T2_SSUB_07_SUM36,
  SUM37	T2_SSUB_07_SUM37,
  GMEMO	T2_SSUB_08_GMEMO
);


CREATE ASCENDING INDEX T2_SSUB_ ON T2_SSUB (ID);
CREATE ASCENDING INDEX T2_SSUB_HCODE ON T2_SSUB (HCODE);
CREATE ASCENDING INDEX T2_SSUB_GDATE ON T2_SSUB (GDATE);

CREATE GENERATOR T2_SSUB_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER T2_SSUB_ID_TNO FOR T2_SSUB 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(T2_SSUB_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;





/* Domain definitions */
CREATE DOMAIN T3_SSUB_01_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN T3_SSUB_02_HCODE AS VARCHAR(5);
CREATE DOMAIN T3_SSUB_03_GDATE AS VARCHAR(10);
CREATE DOMAIN T3_SSUB_04_GCODE AS VARCHAR(5);
CREATE DOMAIN T3_SSUB_05_GNAME AS VARCHAR(24);
CREATE DOMAIN T3_SSUB_06_NAME1 AS VARCHAR(30);
CREATE DOMAIN T3_SSUB_07_NAME2 AS VARCHAR(30);
CREATE DOMAIN T3_SSUB_08_GQUT1 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T3_SSUB_09_GQUT2 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T3_SSUB_10_GQUT3 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T3_SSUB_11_GQUT4 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T3_SSUB_12_GSQUT AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T3_SSUB_13_GSSUM AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T3_SSUB_14_YESNO AS VARCHAR(5);
CREATE DOMAIN T3_SSUB_15_GMEMO AS TimeStamp;

/* Table: T3_SSUB, Owner: SYSDBA */

CREATE TABLE T3_SSUB 
(
  ID	T3_SSUB_01_ID,
  HCODE	T3_SSUB_02_HCODE,
  GDATE	T3_SSUB_03_GDATE,
  GCODE	T3_SSUB_04_GCODE,
  GNAME	T3_SSUB_05_GNAME,
  NAME1	T3_SSUB_06_NAME1,
  NAME2	T3_SSUB_07_NAME2,
  GQUT1	T3_SSUB_08_GQUT1,
  GQUT2	T3_SSUB_09_GQUT2,
  GQUT3	T3_SSUB_10_GQUT3,
  GQUT4	T3_SSUB_11_GQUT4,
  GSQUT	T3_SSUB_12_GSQUT,
  GSSUM	T3_SSUB_13_GSSUM,
  YESNO	T3_SSUB_14_YESNO,
  GMEMO	T3_SSUB_15_GMEMO
);


CREATE ASCENDING INDEX T3_SSUB_ ON T3_SSUB (ID);
CREATE ASCENDING INDEX T3_SSUB_HCODE ON T3_SSUB (HCODE);
CREATE ASCENDING INDEX T3_SSUB_GDATE ON T3_SSUB (GDATE);
CREATE ASCENDING INDEX T3_SSUB_GCODE ON T3_SSUB (GCODE);

CREATE GENERATOR T3_SSUB_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER T3_SSUB_ID_TNO FOR T3_SSUB 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(T3_SSUB_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;





/* Domain definitions */
CREATE DOMAIN T4_SSUB_01_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN T4_SSUB_02_HCODE AS VARCHAR(5);
CREATE DOMAIN T4_SSUB_03_GDATE AS VARCHAR(10);
CREATE DOMAIN T4_SSUB_04_GCODE AS VARCHAR(5);
CREATE DOMAIN T4_SSUB_05_GJISA AS VARCHAR(24);
CREATE DOMAIN T4_SSUB_06_JUBUN AS VARCHAR(30);
CREATE DOMAIN T4_SSUB_07_GQUT1 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T4_SSUB_08_GQUT2 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T4_SSUB_09_GQUT3 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN T4_SSUB_10_GMEMO AS TimeStamp;

/* Table: T4_SSUB, Owner: SYSDBA */

CREATE TABLE T4_SSUB 
(
  ID	T4_SSUB_01_ID,
  HCODE	T4_SSUB_02_HCODE,
  GDATE	T4_SSUB_03_GDATE,
  GCODE	T4_SSUB_04_GCODE,
  GJISA	T4_SSUB_05_GJISA,
  JUBUN	T4_SSUB_06_JUBUN,
  GQUT1	T4_SSUB_07_GQUT1,
  GQUT2	T4_SSUB_08_GQUT2,
  GQUT3	T4_SSUB_09_GQUT3,
  GMEMO	T4_SSUB_10_GMEMO
);


CREATE ASCENDING INDEX T4_SSUB_ ON T4_SSUB (ID);
CREATE ASCENDING INDEX T4_SSUB_HCODE ON T4_SSUB (HCODE);
CREATE ASCENDING INDEX T4_SSUB_GDATE ON T4_SSUB (GDATE);
CREATE ASCENDING INDEX T4_SSUB_GCODE ON T4_SSUB (GCODE);

CREATE GENERATOR T4_SSUB_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER T4_SSUB_ID_TNO FOR T3_SSUB 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(T4_SSUB_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;
