/* Domain definitions */
CREATE DOMAIN G5_GBUN_00_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN G5_GBUN_01_HCODE AS VARCHAR(5);
CREATE DOMAIN G5_GBUN_02_GCODE AS VARCHAR(5);
CREATE DOMAIN G5_GBUN_03_GNAME AS VARCHAR(20);
CREATE DOMAIN G5_GBUN_04_GMEMO AS TimeStamp;

/* Table: G5_GBUN, Owner: SYSDBA */

CREATE TABLE G5_GBUN 
(
  ID	G5_GBUN_00_ID,
  HCODE	G5_GBUN_01_HCODE,
  GCODE	G5_GBUN_02_GCODE,
  GNAME	G5_GBUN_03_GNAME,
  GMEMO	G5_GBUN_04_GMEMO
);

CREATE ASCENDING INDEX G5_GBUN_ ON G5_GBUN (ID);
CREATE ASCENDING INDEX G5_GBUN_HCODE ON G5_GBUN (HCODE);
CREATE ASCENDING INDEX G5_GBUN_GCODE ON G5_GBUN (GCODE);

CREATE GENERATOR G5_GBUN_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER G5_GBUN_ID_TNO FOR G5_GBUN 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(G5_GBUN_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;





/* Domain definitions */
CREATE DOMAIN G5_GGEO_00_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN G5_GGEO_01_HCODE AS VARCHAR(5);
CREATE DOMAIN G5_GGEO_02_GUBUN AS VARCHAR(5);
CREATE DOMAIN G5_GGEO_03_JUBUN AS VARCHAR(6);
CREATE DOMAIN G5_GGEO_04_PUBUN AS VARCHAR(2);
CREATE DOMAIN G5_GGEO_05_SCODE AS VARCHAR(1);
CREATE DOMAIN G5_GGEO_06_GCODE AS VARCHAR(5);
CREATE DOMAIN G5_GGEO_07_OCODE AS VARCHAR(5);
CREATE DOMAIN G5_GGEO_08_GNAME AS VARCHAR(24);
CREATE DOMAIN G5_GGEO_09_GPOSA AS VARCHAR(20);
CREATE DOMAIN G5_GGEO_10_GNUMB AS VARCHAR(12);
CREATE DOMAIN G5_GGEO_11_GUPER AS VARCHAR(20);
CREATE DOMAIN G5_GGEO_12_GJOMO AS VARCHAR(20);
CREATE DOMAIN G5_GGEO_13_GPOST AS VARCHAR(7);
CREATE DOMAIN G5_GGEO_14_GADD1 AS VARCHAR(44);
CREATE DOMAIN G5_GGEO_15_GADD2 AS VARCHAR(44);
CREATE DOMAIN G5_GGEO_16_GTEL1 AS VARCHAR(4);
CREATE DOMAIN G5_GGEO_17_GTEL2 AS VARCHAR(20);
CREATE DOMAIN G5_GGEO_18_GFAX1 AS VARCHAR(4);
CREATE DOMAIN G5_GGEO_19_GFAX2 AS VARCHAR(20);
CREATE DOMAIN G5_GGEO_20_GRAT1 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G5_GGEO_21_GRAT2 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G5_GGEO_22_GRAT3 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G5_GGEO_23_GRAT4 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G5_GGEO_24_GRAT5 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G5_GGEO_25_GRAT6 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G5_GGEO_26_GRAT7 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G5_GGEO_27_GRAT8 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G5_GGEO_28_GRAT9 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G5_GGEO_29_GQUT1 AS DOUBLE PRECISION
	  DEFAULT 0;
CREATE DOMAIN G5_GGEO_30_GPPER AS VARCHAR(10);
CREATE DOMAIN G5_GGEO_31_GBIGO AS VARCHAR(40);
CREATE DOMAIN G5_GGEO_32_NAME1 AS VARCHAR(40);
CREATE DOMAIN G5_GGEO_33_NAME2 AS VARCHAR(40);
CREATE DOMAIN G5_GGEO_34_YESNO AS VARCHAR(5);
CREATE DOMAIN G5_GGEO_35_GPHON AS VARCHAR(15);
CREATE DOMAIN G5_GGEO_36_EMAIL AS VARCHAR(15);
CREATE DOMAIN G5_GGEO_37_GSSUM AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN G5_GGEO_38_GMEMO AS TimeStamp;

/* Table: G5_GGEO, Owner: SYSDBA */

CREATE TABLE G5_GGEO 
(
  ID	G5_GGEO_00_ID,
  HCODE	G5_GGEO_01_HCODE,
  GUBUN	G5_GGEO_02_GUBUN,
  JUBUN	G5_GGEO_03_JUBUN,
  PUBUN	G5_GGEO_04_PUBUN,
  SCODE	G5_GGEO_05_SCODE,
  GCODE	G5_GGEO_06_GCODE,
  OCODE	G5_GGEO_07_OCODE,
  GNAME	G5_GGEO_08_GNAME,
  GPOSA	G5_GGEO_09_GPOSA,
  GNUMB	G5_GGEO_10_GNUMB,
  GUPER	G5_GGEO_11_GUPER,
  GJOMO	G5_GGEO_12_GJOMO,
  GPOST	G5_GGEO_13_GPOST,
  GADD1	G5_GGEO_14_GADD1,
  GADD2	G5_GGEO_15_GADD2,
  GTEL1	G5_GGEO_16_GTEL1,
  GTEL2	G5_GGEO_17_GTEL2,
  GFAX1	G5_GGEO_18_GFAX1,
  GFAX2	G5_GGEO_19_GFAX2,
  GRAT1	G5_GGEO_20_GRAT1,
  GRAT2	G5_GGEO_21_GRAT2,
  GRAT3	G5_GGEO_22_GRAT3,
  GRAT4	G5_GGEO_23_GRAT4,
  GRAT5	G5_GGEO_24_GRAT5,
  GRAT6	G5_GGEO_25_GRAT6,
  GRAT7	G5_GGEO_26_GRAT7,
  GRAT8	G5_GGEO_27_GRAT8,
  GRAT9	G5_GGEO_28_GRAT9,
  GQUT1	G5_GGEO_29_GQUT1,
  GPPER	G5_GGEO_30_GPPER,
  GBIGO	G5_GGEO_31_GBIGO,
  NAME1	G5_GGEO_32_NAME1,
  NAME2	G5_GGEO_33_NAME2,
  YESNO	G5_GGEO_34_YESNO,
  HTEL1	G5_GGEO_35_GPHON,
  EMAIL	G5_GGEO_36_EMAIL,
  GSSUM	G5_GGEO_37_GSSUM,
  GMEMO	G5_GGEO_38_GMEMO
);

CREATE ASCENDING INDEX G5_GGEO_ ON G5_GGEO (ID);
CREATE ASCENDING INDEX G5_GGEO_HCODE ON G5_GGEO (HCODE);
CREATE ASCENDING INDEX G5_GGEO_GCODE ON G5_GGEO (GCODE);
CREATE ASCENDING INDEX G5_GGEO_GNAME ON G5_GGEO (GNAME);

CREATE GENERATOR G5_GGEO_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER G5_GGEO_ID_TNO FOR G5_GGEO 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(G5_GGEO_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;
