/* Domain definitions */
CREATE DOMAIN G4_GBUN_00_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN G4_GBUN_01_HCODE AS VARCHAR(5);
CREATE DOMAIN G4_GBUN_02_GCODE AS VARCHAR(5);
CREATE DOMAIN G4_GBUN_03_GNAME AS VARCHAR(20);
CREATE DOMAIN G4_GBUN_04_GRAT1 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G4_GBUN_05_GRAT2 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G4_GBUN_06_GRAT3 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G4_GBUN_07_GRAT4 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G4_GBUN_08_GMEMO AS TimeStamp;

/* Table: G4_GBUN, Owner: SYSDBA */

CREATE TABLE G4_GBUN 
(
  ID	G4_GBUN_00_ID,
  HCODE	G4_GBUN_01_HCODE,
  GCODE	G4_GBUN_02_GCODE,
  GNAME	G4_GBUN_03_GNAME,
  GRAT1	G4_GBUN_04_GRAT1,
  GRAT2 G4_GBUN_05_GRAT2,
  GRAT3	G4_GBUN_06_GRAT3,
  GRAT4	G4_GBUN_07_GRAT4,
  GMEMO	G4_GBUN_08_GMEMO
);

CREATE ASCENDING INDEX G4_GBUN_ ON G4_GBUN (ID);
CREATE ASCENDING INDEX G4_GBUN_HCODE ON G4_GBUN (HCODE);
CREATE ASCENDING INDEX G4_GBUN_GCODE ON G4_GBUN (GCODE);

CREATE GENERATOR G4_GBUN_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER G4_GBUN_ID_TNO FOR G4_GBUN 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(G4_GBUN_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;





/* Domain definitions */
CREATE DOMAIN G4_BOOK_00_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN G4_BOOK_01_HCODE AS VARCHAR(5);
CREATE DOMAIN G4_BOOK_02_GUBUN AS VARCHAR(5);
CREATE DOMAIN G4_BOOK_03_JUBUN AS VARCHAR(6);
CREATE DOMAIN G4_BOOK_04_SCODE AS VARCHAR(1);
CREATE DOMAIN G4_BOOK_05_GCODE AS VARCHAR(10);
CREATE DOMAIN G4_BOOK_06_OCODE AS VARCHAR(10);
CREATE DOMAIN G4_BOOK_07_GNAME AS VARCHAR(40);
CREATE DOMAIN G4_BOOK_08_GJEJA AS VARCHAR(20);
CREATE DOMAIN G4_BOOK_09_GDABI AS VARCHAR(5);
CREATE DOMAIN G4_BOOK_10_GDANG AS DOUBLE PRECISION;
CREATE DOMAIN G4_BOOK_11_GISBN AS VARCHAR(20);
CREATE DOMAIN G4_BOOK_12_GRAT1 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G4_BOOK_13_GRAT2 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G4_BOOK_14_GRAT3 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G4_BOOK_15_GRAT4 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G4_BOOK_16_GRAT5 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G4_BOOK_17_GRAT6 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G4_BOOK_18_GRAT7 AS SMALLINT
	 DEFAULT 0;
CREATE DOMAIN G4_BOOK_19_GRAT8 AS SMALLINT
	 DEFAULT 0;
CREATE DOMAIN G4_BOOK_20_GRAT9 AS SMALLINT
	 DEFAULT 0;
CREATE DOMAIN G4_BOOK_21_GBJIL AS VARCHAR(6);
CREATE DOMAIN G4_BOOK_22_GBIGO AS VARCHAR(40);
CREATE DOMAIN G4_BOOK_23_YESNO AS VARCHAR(5);
CREATE DOMAIN G4_BOOK_24_DATE1 AS VARCHAR(10);
CREATE DOMAIN G4_BOOK_25_DATE2 AS VARCHAR(10);
CREATE DOMAIN G4_BOOK_26_GNUMB AS VARCHAR(20);
CREATE DOMAIN G4_BOOK_27_NAME1 AS VARCHAR(40);
CREATE DOMAIN G4_BOOK_28_NAME2 AS VARCHAR(40);
CREATE DOMAIN G4_BOOK_29_GPAGE AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN G4_BOOK_30_GPAN1 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN G4_BOOK_31_GPAN2 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN G4_BOOK_32_JEJA1 AS VARCHAR(20);
CREATE DOMAIN G4_BOOK_33_JEJA2 AS VARCHAR(20);
CREATE DOMAIN G4_BOOK_34_GPOST AS VARCHAR(20);
CREATE DOMAIN G4_BOOK_35_BCODE AS VARCHAR(13);
CREATE DOMAIN G4_BOOK_36_GSSUM AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN G4_BOOK_37_GMEMO AS TimeStamp;

/* Table: G4_BOOK, Owner: SYSDBA */

CREATE TABLE G4_BOOK 
(
  ID	G4_BOOK_00_ID,
  HCODE	G4_BOOK_01_HCODE,
  GUBUN	G4_BOOK_02_GUBUN,
  JUBUN	G4_BOOK_03_JUBUN,
  SCODE	G4_BOOK_04_SCODE,
  GCODE	G4_BOOK_05_GCODE,
  OCODE	G4_BOOK_06_OCODE,
  GNAME	G4_BOOK_07_GNAME,
  GJEJA	G4_BOOK_08_GJEJA,
  GDABI	G4_BOOK_09_GDABI,
  GDANG	G4_BOOK_10_GDANG,
  GISBN	G4_BOOK_11_GISBN,
  GRAT1	G4_BOOK_12_GRAT1,
  GRAT2	G4_BOOK_13_GRAT2,
  GRAT3	G4_BOOK_14_GRAT3,
  GRAT4	G4_BOOK_15_GRAT4,
  GRAT5	G4_BOOK_16_GRAT5,
  GRAT6	G4_BOOK_17_GRAT6,
  GRAT7	G4_BOOK_18_GRAT7,
  GRAT8	G4_BOOK_19_GRAT8,
  GRAT9	G4_BOOK_20_GRAT9,
  GBJIL	G4_BOOK_21_GBJIL,
  GBIGO	G4_BOOK_22_GBIGO,
  YESNO	G4_BOOK_23_YESNO,
  DATE1	G4_BOOK_24_DATE1,
  DATE2	G4_BOOK_25_DATE2,
  GNUMB	G4_BOOK_26_GNUMB,
  NAME1	G4_BOOK_27_NAME1,
  NAME2	G4_BOOK_28_NAME2,
  GPAGE	G4_BOOK_29_GPAGE,
  GPAN1	G4_BOOK_30_GPAN1,
  GPAN2	G4_BOOK_31_GPAN2,
  JEJA1	G4_BOOK_32_JEJA1,
  JEJA2	G4_BOOK_33_JEJA2,
  GPOST	G4_BOOK_34_GPOST,
  BCODE	G4_BOOK_35_BCODE,
  GSSUM	G4_BOOK_36_GSSUM,
  GMEMO	G4_BOOK_37_GMEMO
);

CREATE ASCENDING INDEX G4_BOOK_ ON G4_BOOK (ID);
CREATE ASCENDING INDEX G4_BOOK_HCODE ON G4_BOOK (HCODE);
CREATE ASCENDING INDEX G4_BOOK_GCODE ON G4_BOOK (GCODE);
CREATE ASCENDING INDEX G4_BOOK_GNAME ON G4_BOOK (GNAME);

CREATE GENERATOR G4_BOOK_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER G4_BOOK_ID_TNO FOR G4_BOOK 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(G4_BOOK_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;
