/* Domain definitions */
CREATE DOMAIN G6_GGEO_00_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN G6_GGEO_01_HCODE AS VARCHAR(5);
CREATE DOMAIN G6_GGEO_02_GCODE AS VARCHAR(5);
CREATE DOMAIN G6_GGEO_03_BCODE AS VARCHAR(10);
CREATE DOMAIN G6_GGEO_04_GRAT1 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G6_GGEO_05_GRAT2 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G6_GGEO_06_GRAT3 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G6_GGEO_07_GRAT4 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G6_GGEO_08_GRAT5 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G6_GGEO_09_GRAT6 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G6_GGEO_10_GRAT7 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G6_GGEO_11_GRAT8 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G6_GGEO_12_GRAT9 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN G6_GGEO_13_GSSUM AS DOUBLE PRECISION
	  DEFAULT 0;
CREATE DOMAIN G6_GGEO_14_GMEMO AS TimeStamp;

/* Table: G6_GGEO, Owner: SYSDBA */

CREATE TABLE G6_GGEO 
(
  ID	G6_GGEO_00_ID,
  HCODE	G6_GGEO_01_HCODE,
  GCODE	G6_GGEO_02_GCODE,
  BCODE	G6_GGEO_03_BCODE,
  GRAT1	G6_GGEO_04_GRAT1,
  GRAT2	G6_GGEO_05_GRAT2,
  GRAT3	G6_GGEO_06_GRAT3,
  GRAT4	G6_GGEO_07_GRAT4,
  GRAT5	G6_GGEO_08_GRAT5,
  GRAT6	G6_GGEO_09_GRAT6,
  GRAT7	G6_GGEO_10_GRAT7,
  GRAT8	G6_GGEO_11_GRAT8,
  GRAT9	G6_GGEO_12_GRAT9,
  GSSUM	G6_GGEO_13_GSSUM,
  GMEMO	G6_GGEO_14_GMEMO
);

CREATE ASCENDING INDEX G6_GGEO_ ON G6_GGEO (ID);
CREATE ASCENDING INDEX G6_GGEO_HCODE ON G6_GGEO (HCODE);
CREATE ASCENDING INDEX G6_GGEO_GCODE ON G6_GGEO (GCODE);
CREATE ASCENDING INDEX G6_GGEO_BCODE ON G6_GGEO (BCODE);

CREATE GENERATOR G6_GGEO_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER G6_GGEO_ID_TNO FOR G6_GGEO 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(G6_GGEO_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;
