/* Domain definitions */
CREATE DOMAIN G3_GBUN_00_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN G3_GBUN_01_HCODE AS VARCHAR(5);
CREATE DOMAIN G3_GBUN_02_GCODE AS VARCHAR(5);
CREATE DOMAIN G3_GBUN_03_GNAME AS VARCHAR(20);
CREATE DOMAIN G3_GBUN_04_GMEMO AS TimeStamp;

/* Table: G3_GBUN, Owner: SYSDBA */

CREATE TABLE G3_GBUN 
(
  ID	G3_GBUN_00_ID,
  HCODE	G3_GBUN_01_HCODE,
  GCODE	G3_GBUN_02_GCODE,
  GNAME	G3_GBUN_03_GNAME,
  GMEMO	G3_GBUN_04_GMEMO
);

CREATE ASCENDING INDEX G3_GBUN_ ON G3_GBUN (ID);
CREATE ASCENDING INDEX G3_GBUN_HCODE ON G3_GBUN (HCODE);
CREATE ASCENDING INDEX G3_GBUN_GCODE ON G3_GBUN (GCODE);

CREATE GENERATOR G3_GBUN_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER G3_GBUN_ID_TNO FOR G3_GBUN 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(G3_GBUN_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;





/* Domain definitions */
CREATE DOMAIN G3_GJEO_00_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN G3_GJEO_01_HCODE AS VARCHAR(5);
CREATE DOMAIN G3_GJEO_02_GUBUN AS VARCHAR(5);
CREATE DOMAIN G3_GJEO_03_SCODE AS VARCHAR(1);
CREATE DOMAIN G3_GJEO_04_GCODE AS VARCHAR(5);
CREATE DOMAIN G3_GJEO_05_GPOSA AS VARCHAR(20);
CREATE DOMAIN G3_GJEO_06_GNAME AS VARCHAR(24);
CREATE DOMAIN G3_GJEO_07_DATE1 AS VARCHAR(10);
CREATE DOMAIN G3_GJEO_08_DATE2 AS VARCHAR(10);
CREATE DOMAIN G3_GJEO_09_GJICE AS VARCHAR(20);
CREATE DOMAIN G3_GJEO_10_GSCHO AS VARCHAR(20);
CREATE DOMAIN G3_GJEO_11_GNUMB AS VARCHAR(20);
CREATE DOMAIN G3_GJEO_12_GNUM1 AS VARCHAR(20);
CREATE DOMAIN G3_GJEO_13_GNUM2 AS VARCHAR(20);
CREATE DOMAIN G3_GJEO_14_GTEL1 AS VARCHAR(4);
CREATE DOMAIN G3_GJEO_15_GTEL2 AS VARCHAR(9);
CREATE DOMAIN G3_GJEO_16_GFAX1 AS VARCHAR(4);
CREATE DOMAIN G3_GJEO_17_GFAX2 AS VARCHAR(9);
CREATE DOMAIN G3_GJEO_18_GPOST AS VARCHAR(7);
CREATE DOMAIN G3_GJEO_19_GADD1 AS VARCHAR(44);
CREATE DOMAIN G3_GJEO_20_GADD2 AS VARCHAR(44);
CREATE DOMAIN G3_GJEO_21_OPOST AS VARCHAR(7);
CREATE DOMAIN G3_GJEO_22_OADD1 AS VARCHAR(44);
CREATE DOMAIN G3_GJEO_23_OADD2 AS VARCHAR(44);
CREATE DOMAIN G3_GJEO_24_GBIGO AS VARCHAR(40);
CREATE DOMAIN G3_GJEO_25_GMEMO AS TimeStamp;

/* Table: G3_GJEO, Owner: SYSDBA */

CREATE TABLE G3_GJEO 
(
  ID	G3_GJEO_00_ID,
  HCODE	G3_GJEO_01_HCODE,
  GUBUN	G3_GJEO_02_GUBUN,
  SCODE	G3_GJEO_03_SCODE,
  GCODE	G3_GJEO_04_GCODE,
  GPOSA	G3_GJEO_05_GPOSA,
  GNAME	G3_GJEO_06_GNAME,
  DATE1	G3_GJEO_07_DATE1,
  DATE2	G3_GJEO_08_DATE2,
  GJICE	G3_GJEO_09_GJICE,
  GSCHO	G3_GJEO_10_GSCHO,
  GNUMB	G3_GJEO_11_GNUMB,
  GNUM1	G3_GJEO_12_GNUM1,
  GNUM2	G3_GJEO_13_GNUM2,
  GTEL1	G3_GJEO_14_GTEL1,
  GTEL2	G3_GJEO_15_GTEL2,
  GFAX1	G3_GJEO_16_GFAX1,
  GFAX2	G3_GJEO_17_GFAX2,
  GPOST	G3_GJEO_18_GPOST,
  GADD1	G3_GJEO_19_GADD1,
  GADD2	G3_GJEO_20_GADD2,
  OPOST	G3_GJEO_21_OPOST,
  OADD1	G3_GJEO_22_OADD1,
  OADD2	G3_GJEO_23_OADD2,
  GBIGO	G3_GJEO_24_GBIGO,
  GMEMO	G3_GJEO_25_GMEMO
);

CREATE ASCENDING INDEX G3_GJEO_ ON G3_GJEO (ID);
CREATE ASCENDING INDEX G3_GJEO_HCODE ON G3_GJEO (HCODE);
CREATE ASCENDING INDEX G3_GJEO_GCODE ON G3_GJEO (GCODE);
CREATE ASCENDING INDEX G3_GJEO_GNAME ON G3_GJEO (GNAME);

CREATE GENERATOR G3_GJEO_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER G3_GJEO_ID_TNO FOR G3_GJEO 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(G3_GJEO_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;
