/* Domain definitions */
CREATE DOMAIN S1_SSUB_01_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN S1_SSUB_01_IDNUM AS DOUBLE PRECISION;
CREATE DOMAIN S1_SSUB_02_GDATE AS VARCHAR(10);
CREATE DOMAIN S1_SSUB_03_SCODE AS VARCHAR(1);
CREATE DOMAIN S1_SSUB_04_GCODE AS VARCHAR(5);
CREATE DOMAIN S1_SSUB_05_HCODE AS VARCHAR(5);
CREATE DOMAIN S1_SSUB_06_OCODE AS VARCHAR(1);
CREATE DOMAIN S1_SSUB_07_BCODE AS VARCHAR(10);
CREATE DOMAIN S1_SSUB_08_GUBUN AS VARCHAR(4);
CREATE DOMAIN S1_SSUB_09_JUBUN AS VARCHAR(2);
CREATE DOMAIN S1_SSUB_10_PUBUN AS VARCHAR(4);
CREATE DOMAIN S1_SSUB_11_GSQUT AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN S1_SSUB_11_QSQUT AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN S1_SSUB_12_GDANG AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN S1_SSUB_13_GRAT1 AS SMALLINT
	 DEFAULT 0;
CREATE DOMAIN S1_SSUB_14_GSSUM AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN S1_SSUB_14_JEAGO AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN S1_SSUB_15_GBIGO AS VARCHAR(20);
CREATE DOMAIN S1_SSUB_16_YESNO AS VARCHAR(5);
CREATE DOMAIN S1_SSUB_17_GJISA AS VARCHAR(15);
CREATE DOMAIN S1_SSUB_18_GMEMO AS TimeStamp;

/* Table: S1_SSUB, Owner: SYSDBA */

CREATE TABLE S1_SSUB 
(
  ID	S1_SSUB_01_ID,
  IDNUM	S1_SSUB_01_IDNUM,
  GDATE	S1_SSUB_02_GDATE,
  SCODE	S1_SSUB_03_SCODE,
  GCODE	S1_SSUB_04_GCODE,
  HCODE	S1_SSUB_05_HCODE,
  OCODE	S1_SSUB_06_OCODE,
  BCODE	S1_SSUB_07_BCODE,
  GUBUN	S1_SSUB_08_GUBUN,
  JUBUN	S1_SSUB_09_JUBUN,
  PUBUN	S1_SSUB_10_PUBUN,
  GSQUT	S1_SSUB_11_GSQUT,
  QSQUT	S1_SSUB_11_QSQUT,
  GDANG	S1_SSUB_12_GDANG,
  GRAT1	S1_SSUB_13_GRAT1,
  GSSUM	S1_SSUB_14_GSSUM,
  JEAGO	S1_SSUB_14_JEAGO,
  GBIGO	S1_SSUB_15_GBIGO,
  YESNO	S1_SSUB_16_YESNO,
  GJISA	S1_SSUB_17_GJISA,
  GMEMO	S1_SSUB_18_GMEMO
);

CREATE ASCENDING INDEX S1_SSUB_ ON S1_SSUB (ID);
CREATE ASCENDING INDEX S1_SSUB_HCODE ON S1_SSUB (HCODE);
CREATE ASCENDING INDEX S1_SSUB_GDATE ON S1_SSUB (GDATE);
CREATE ASCENDING INDEX S1_SSUB_GCODE ON S1_SSUB (GCODE);
CREATE ASCENDING INDEX S1_SSUB_BCODE ON S1_SSUB (BCODE);

CREATE GENERATOR S1_SSUB_ID_GEN;
CREATE GENERATOR S1_SSUB_ID_NUM;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER S1_SSUB_ID_NUM FOR S1_SSUB 
ACTIVE BEFORE INSERT POSITION 0
as
DECLARE VARIABLE Idmax INTEGER;
DECLARE VARIABLE Idmin INTEGER;
Begin
  IF (New.Gubun='√‚∞Ì') Then Begin
  Select Max(Idnum) From S1_Ssub
  Where (S1_Ssub.Gdate = New.Gdate) AND (S1_Ssub.Scode = New.Scode) AND
        (S1_Ssub.Gcode = New.Gcode) AND (S1_Ssub.Jubun = New.Jubun) AND
        (S1_Ssub.Gjisa = New.Gjisa)
  INTO Idmax;
  if ((Idmax IS NULL)OR(Idmax = 0)) Then begin
    Select Max(Idnum) From S1_Ssub
    Where (S1_Ssub.Gdate = New.Gdate)
    INTO Idmin;
    if ((Idmin IS NULL)OR(Idmin = 0)) Then
    Idmax =(1);
    else
    Idmax =(Idmin+1);
  end else begin
    Idmax = Idmax;
  end
  New.Idnum = Idmax;
  End
  Else
  New.Idnum = 0;
End;

CREATE TRIGGER S1_SSUB_ID_TNO FOR S1_SSUB 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(S1_SSUB_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;





/* Domain definitions */
CREATE DOMAIN S1_MEMO_01_ID AS DOUBLE PRECISION
	 DEFAULT 0 NOT NULL;
CREATE DOMAIN S1_MEMO_02_GDATE AS VARCHAR(10);
CREATE DOMAIN S1_MEMO_03_SCODE AS VARCHAR(1);
CREATE DOMAIN S1_MEMO_04_GCODE AS VARCHAR(5);
CREATE DOMAIN S1_MEMO_05_HCODE AS VARCHAR(5);
CREATE DOMAIN S1_MEMO_06_GUBUN AS VARCHAR(4);
CREATE DOMAIN S1_MEMO_07_JUBUN AS VARCHAR(2);
CREATE DOMAIN S1_MEMO_08_GBIGO AS VARCHAR(50);
CREATE DOMAIN S1_MEMO_08_SBIGO AS VARCHAR(50);
CREATE DOMAIN S1_MEMO_08_GTEL1 AS VARCHAR(20);
CREATE DOMAIN S1_MEMO_08_GTEL2 AS VARCHAR(20);
CREATE DOMAIN S1_MEMO_08_GNAME AS VARCHAR(30);
CREATE DOMAIN S1_MEMO_09_GJISA AS VARCHAR(15);
CREATE DOMAIN S1_MEMO_10_GMEMO AS TimeStamp;

/* Table: S1_MEMO, Owner: SYSDBA */

CREATE TABLE S1_MEMO 
(
  ID	S1_MEMO_01_ID,
  GDATE	S1_MEMO_02_GDATE,
  SCODE	S1_MEMO_03_SCODE,
  GCODE	S1_MEMO_04_GCODE,
  HCODE	S1_MEMO_05_HCODE,
  GUBUN	S1_MEMO_06_GUBUN,
  JUBUN	S1_MEMO_07_JUBUN,
  GBIGO	S1_MEMO_08_GBIGO,
  SBIGO	S1_MEMO_08_SBIGO,
  GTEL1	S1_MEMO_08_GTEL1,
  GTEL2	S1_MEMO_08_GTEL2,
  GNAME	S1_MEMO_08_GNAME,
  GJISA	S1_MEMO_09_GJISA,
  GMEMO	S1_MEMO_10_GMEMO
);

CREATE ASCENDING INDEX S1_MEMO_ ON S1_MEMO (ID);
CREATE ASCENDING INDEX S1_MEMO_HCODE ON S1_MEMO (HCODE);
CREATE ASCENDING INDEX S1_MEMO_GDATE ON S1_MEMO (GDATE);
CREATE ASCENDING INDEX S1_MEMO_GCODE ON S1_MEMO (GCODE);

CREATE GENERATOR S1_MEMO_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER S1_MEMO_ID_TNO FOR S1_MEMO 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(S1_MEMO_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;





/* Domain definitions */
CREATE DOMAIN S2_SSUB_00_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN S2_SSUB_01_YCODE AS VARCHAR(5);
CREATE DOMAIN S2_SSUB_02_GDATE AS VARCHAR(10);
CREATE DOMAIN S2_SSUB_03_GUBUN AS VARCHAR(10);
CREATE DOMAIN S2_SSUB_04_SCODE AS VARCHAR(1);
CREATE DOMAIN S2_SSUB_05_GCODE AS VARCHAR(5);
CREATE DOMAIN S2_SSUB_06_GNAME AS VARCHAR(24);
CREATE DOMAIN S2_SSUB_07_HCODE AS VARCHAR(1);
CREATE DOMAIN S2_SSUB_08_OCODE AS VARCHAR(5);
CREATE DOMAIN S2_SSUB_09_ONAME AS VARCHAR(24);
CREATE DOMAIN S2_SSUB_10_BCODE AS VARCHAR(10);
CREATE DOMAIN S2_SSUB_11_JUBUN AS VARCHAR(20);
CREATE DOMAIN S2_SSUB_12_GSQUT AS DOUBLE PRECISION
	  DEFAULT 0;
CREATE DOMAIN S2_SSUB_13_GDANG AS DOUBLE PRECISION
	  DEFAULT 0;
CREATE DOMAIN S2_SSUB_14_GSSUM AS DOUBLE PRECISION
	  DEFAULT 0;
CREATE DOMAIN S2_SSUB_15_GBIGO AS VARCHAR(20);
CREATE DOMAIN S2_SSUB_16_GMEMO AS TimeStamp;

/* Table: S2_SSUB, Owner: SYSDBA */

CREATE TABLE S2_SSUB 
(
  ID	S2_SSUB_00_ID,
  YCODE	S2_SSUB_01_YCODE,
  GDATE	S2_SSUB_02_GDATE,
  GUBUN	S2_SSUB_03_GUBUN,
  SCODE	S2_SSUB_04_SCODE,
  GCODE	S2_SSUB_05_GCODE,
  GNAME	S2_SSUB_06_GNAME,
  HCODE	S2_SSUB_07_HCODE,
  OCODE	S2_SSUB_08_OCODE,
  ONAME	S2_SSUB_09_ONAME,
  BCODE	S2_SSUB_10_BCODE,
  JUBUN	S2_SSUB_11_JUBUN,
  GSQUT	S2_SSUB_12_GSQUT,
  GDANG	S2_SSUB_13_GDANG,
  GSSUM	S2_SSUB_14_GSSUM,
  GBIGO	S2_SSUB_15_GBIGO,
  GMEMO	S2_SSUB_16_GMEMO
);

CREATE ASCENDING INDEX S2_SSUB_ ON S2_SSUB (ID);
CREATE ASCENDING INDEX S2_SSUB_HCODE ON S2_SSUB (HCODE);
CREATE ASCENDING INDEX S2_SSUB_GDATE ON S2_SSUB (GDATE);
CREATE ASCENDING INDEX S2_SSUB_GCODE ON S2_SSUB (GCODE);

CREATE GENERATOR S2_SSUB_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER S2_SSUB_ID_TNO FOR S2_SSUB 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(S2_SSUB_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;





/* Domain definitions */
CREATE DOMAIN S3_SSUB_00_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN S3_SSUB_01_HCODE AS VARCHAR(5);
CREATE DOMAIN S3_SSUB_02_GCODE AS VARCHAR(5);
CREATE DOMAIN S3_SSUB_03_GNAME AS VARCHAR(20);
CREATE DOMAIN S3_SSUB_04_GDATE AS VARCHAR(10);
CREATE DOMAIN S3_SSUB_05_BCODE AS VARCHAR(10);
CREATE DOMAIN S3_SSUB_06_GSSUM AS DOUBLE PRECISION
	  DEFAULT 0;
CREATE DOMAIN S3_SSUB_07_GRAT1 AS DOUBLE PRECISION
	  DEFAULT 0;
CREATE DOMAIN S3_SSUB_08_GISUM AS DOUBLE PRECISION
	  DEFAULT 0;
CREATE DOMAIN S3_SSUB_09_GOSUM AS DOUBLE PRECISION
	  DEFAULT 0;
CREATE DOMAIN S3_SSUB_10_GBSUM AS DOUBLE PRECISION
	  DEFAULT 0;
CREATE DOMAIN S3_SSUB_11_GMEMO AS TimeStamp;

/* Table: S3_SSUB, Owner: SYSDBA */

CREATE TABLE S3_SSUB 
(
  ID	S3_SSUB_00_ID,
  HCODE	S3_SSUB_01_HCODE,
  GCODE	S3_SSUB_02_GCODE,
  GNAME	S3_SSUB_03_GNAME,
  GDATE	S3_SSUB_04_GDATE,
  BCODE	S3_SSUB_05_BCODE,
  GSSUM	S3_SSUB_06_GSSUM,
  GRAT1	S3_SSUB_07_GRAT1,
  GISUM	S3_SSUB_08_GISUM,
  GOSUM	S3_SSUB_09_GOSUM,
  GBSUM	S3_SSUB_10_GBSUM,
  GMEMO	S3_SSUB_11_GMEMO
);

CREATE ASCENDING INDEX S3_SSUB_ ON S3_SSUB (ID);
CREATE ASCENDING INDEX S3_SSUB_HCODE ON S3_SSUB (HCODE);
CREATE ASCENDING INDEX S3_SSUB_GDATE ON S3_SSUB (GDATE);
CREATE ASCENDING INDEX S3_SSUB_GCODE ON S3_SSUB (GCODE);

CREATE GENERATOR S3_SSUB_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER S3_SSUB_ID_TNO FOR S3_SSUB 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(S3_SSUB_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;
