/* Domain definitions */
CREATE DOMAIN H1_GBUN_00_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN H1_GBUN_01_HCODE AS VARCHAR(5);
CREATE DOMAIN H1_GBUN_02_SCODE AS VARCHAR(1);
CREATE DOMAIN H1_GBUN_03_GCODE AS VARCHAR(5);
CREATE DOMAIN H1_GBUN_04_GNAME AS VARCHAR(20);
CREATE DOMAIN H1_GBUN_05_ONAME AS VARCHAR(40);
CREATE DOMAIN H1_GBUN_06_GDATE AS VARCHAR(10);
CREATE DOMAIN H1_GBUN_07_CLAS1 AS DOUBLE PRECISION
	  DEFAULT 0;
CREATE DOMAIN H1_GBUN_08_CLAS2 AS DOUBLE PRECISION
	  DEFAULT 0;
CREATE DOMAIN H1_GBUN_09_CLAS3 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN H1_GBUN_10_GSUM1 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN H1_GBUN_11_GSUM2 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN H1_GBUN_12_GSUM3 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN H1_GBUN_13_GMEMO AS TimeStamp;

/* Table: H1_GBUN, Owner: SYSDBA */

CREATE TABLE H1_GBUN 
(
  ID	H1_GBUN_00_ID,
  HCODE	H1_GBUN_01_HCODE,
  SCODE	H1_GBUN_02_SCODE,
  GCODE	H1_GBUN_03_GCODE,
  GNAME	H1_GBUN_04_GNAME,
  ONAME	H1_GBUN_05_ONAME,
  GDATE	H1_GBUN_06_GDATE,
  CLAS1	H1_GBUN_07_CLAS1,
  CLAS2	H1_GBUN_08_CLAS2,
  CLAS3	H1_GBUN_09_CLAS3,
  GSUM1	H1_GBUN_10_GSUM1,
  GSUM2	H1_GBUN_11_GSUM2,
  GSUM3	H1_GBUN_12_GSUM3,
  GMEMO	H1_GBUN_13_GMEMO
);


CREATE ASCENDING INDEX H1_GBUN_ ON H1_GBUN (ID);
CREATE ASCENDING INDEX H1_GBUN_HCODE ON H1_GBUN (HCODE);
CREATE ASCENDING INDEX H1_GBUN_GCODE ON H1_GBUN (GCODE);

CREATE GENERATOR H1_GBUN_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER H1_GBUN_ID_TNO FOR H1_GBUN 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(H1_GBUN_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;





/* Domain definitions */
CREATE DOMAIN H2_GBUN_00_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN H2_GBUN_01_HCODE AS VARCHAR(5);
CREATE DOMAIN H2_GBUN_02_SCODE AS VARCHAR(1);
CREATE DOMAIN H2_GBUN_03_GCODE AS VARCHAR(5);
CREATE DOMAIN H2_GBUN_04_GNAME AS VARCHAR(20);
CREATE DOMAIN H2_GBUN_05_ONAME AS VARCHAR(40);
CREATE DOMAIN H2_GBUN_06_JUBUN AS VARCHAR(40);
CREATE DOMAIN H2_GBUN_07_GDATE AS VARCHAR(10);
CREATE DOMAIN H2_GBUN_08_CLAS1 AS DOUBLE PRECISION
	  DEFAULT 0;
CREATE DOMAIN H2_GBUN_09_CLAS2 AS DOUBLE PRECISION
	  DEFAULT 0;
CREATE DOMAIN H2_GBUN_10_CLAS3 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN H2_GBUN_11_GSUM1 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN H2_GBUN_12_GSUM2 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN H2_GBUN_13_GSUM3 AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN H2_GBUN_14_GBIGO AS VARCHAR(40);
CREATE DOMAIN H2_GBUN_15_GMEMO AS TimeStamp;

/* Table: H2_GBUN, Owner: SYSDBA */

CREATE TABLE H2_GBUN 
(
  ID	H2_GBUN_00_ID,
  HCODE	H2_GBUN_01_HCODE,
  SCODE	H2_GBUN_02_SCODE,
  GCODE	H2_GBUN_03_GCODE,
  GNAME	H2_GBUN_04_GNAME,
  ONAME	H2_GBUN_05_ONAME,
  JUBUN	H2_GBUN_06_JUBUN,
  GDATE	H2_GBUN_07_GDATE,
  CLAS1	H2_GBUN_08_CLAS1,
  CLAS2	H2_GBUN_09_CLAS2,
  CLAS3	H2_GBUN_10_CLAS3,
  GSUM1	H2_GBUN_11_GSUM1,
  GSUM2	H2_GBUN_12_GSUM2,
  GSUM3	H2_GBUN_13_GSUM3,
  GBIGO	H2_GBUN_14_GBIGO,
  GMEMO	H2_GBUN_15_GMEMO
);


CREATE ASCENDING INDEX H2_GBUN_ ON H2_GBUN (ID);
CREATE ASCENDING INDEX H2_GBUN_HCODE ON H2_GBUN (HCODE);
CREATE ASCENDING INDEX H2_SSUB_GCODE ON H2_GBUN (GCODE);

CREATE GENERATOR H2_GBUN_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER H2_GBUN_ID_TNO FOR H2_GBUN 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(H2_GBUN_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;





/* Domain definitions */
CREATE DOMAIN H1_SSUB_01_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN H1_SSUB_02_IDNUM AS DOUBLE PRECISION;
CREATE DOMAIN H1_SSUB_03_GDATE AS VARCHAR(10);
CREATE DOMAIN H1_SSUB_04_GUBUN AS VARCHAR(4);
CREATE DOMAIN H1_SSUB_05_HCODE AS VARCHAR(5);
CREATE DOMAIN H1_SSUB_06_SCODE AS VARCHAR(1);
CREATE DOMAIN H1_SSUB_07_GCODE AS VARCHAR(5);
CREATE DOMAIN H1_SSUB_08_GNAME AS VARCHAR(24);
CREATE DOMAIN H1_SSUB_09_TCODE AS VARCHAR(1);
CREATE DOMAIN H1_SSUB_10_OCODE AS VARCHAR(5);
CREATE DOMAIN H1_SSUB_11_ONAME AS VARCHAR(20);
CREATE DOMAIN H1_SSUB_12_GSSUM AS DOUBLE PRECISION
	 DEFAULT 0;
CREATE DOMAIN H1_SSUB_13_PUBUN AS VARCHAR(4);
CREATE DOMAIN H1_SSUB_14_GBIGO AS VARCHAR(15);
CREATE DOMAIN H1_SSUB_15_GMEMO AS TimeStamp;

/* Table: H1_SSUB, Owner: SYSDBA */

CREATE TABLE H1_SSUB 
(
  ID	H1_SSUB_01_ID,
  IDNUM	H1_SSUB_02_IDNUM,
  GDATE	H1_SSUB_03_GDATE,
  GUBUN	H1_SSUB_04_GUBUN,
  HCODE	H1_SSUB_05_HCODE,
  SCODE	H1_SSUB_06_SCODE,
  GCODE	H1_SSUB_07_GCODE,
  GNAME	H1_SSUB_08_GNAME,
  TCODE	H1_SSUB_09_TCODE,
  OCODE	H1_SSUB_10_OCODE,
  ONAME	H1_SSUB_11_ONAME,
  GSSUM	H1_SSUB_12_GSSUM,
  PUBUN	H1_SSUB_13_PUBUN,
  GBIGO	H1_SSUB_14_GBIGO,
  GMEMO	H1_SSUB_15_GMEMO
);


CREATE ASCENDING INDEX H1_SSUB_ ON H1_SSUB (ID);
CREATE ASCENDING INDEX H1_SSUB_HCODE ON H1_SSUB (HCODE);
CREATE ASCENDING INDEX H1_SSUB_GDATE ON H1_SSUB (GDATE);
CREATE ASCENDING INDEX H1_SSUB_GCODE ON H1_SSUB (GCODE);

CREATE GENERATOR H1_SSUB_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER H1_SSUB_ID_TNO FOR H1_SSUB 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(H1_SSUB_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;





/* Domain definitions */
CREATE DOMAIN H4_IYEO_00_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN H4_IYEO_01_HCODE AS VARCHAR(5);
CREATE DOMAIN H4_IYEO_02_GNUMB AS VARCHAR(12);
CREATE DOMAIN H4_IYEO_03_GNAME AS VARCHAR(20);
CREATE DOMAIN H4_IYEO_04_GPOSA AS VARCHAR(20);
CREATE DOMAIN H4_IYEO_05_DATE1 AS VARCHAR(10);
CREATE DOMAIN H4_IYEO_06_DATE2 AS VARCHAR(10);
CREATE DOMAIN H4_IYEO_07_DATE3 AS VARCHAR(10);
CREATE DOMAIN H4_IYEO_08_DATE4 AS VARCHAR(10);
CREATE DOMAIN H4_IYEO_09_GBANG AS VARCHAR(12);
CREATE DOMAIN H4_IYEO_10_NAME1 AS VARCHAR(12);
CREATE DOMAIN H4_IYEO_11_NAME2 AS VARCHAR(20);
CREATE DOMAIN H4_IYEO_12_SCODE AS VARCHAR(8);
CREATE DOMAIN H4_IYEO_13_GRAT1 AS SMALLINT
	  DEFAULT 0;
CREATE DOMAIN H4_IYEO_14_GOSUM AS DOUBLE PRECISION
	  DEFAULT 0;
CREATE DOMAIN H4_IYEO_15_GSSUM AS DOUBLE PRECISION
	  DEFAULT 0;
CREATE DOMAIN H4_IYEO_16_GBIGO AS VARCHAR(50);
CREATE DOMAIN H4_IYEO_17_GMEMO AS TimeStamp;

/* Table: H4_IYEO, Owner: SYSDBA */

CREATE TABLE H4_IYEO 
(
  ID	H4_IYEO_00_ID,
  HCODE	H4_IYEO_01_HCODE,
  GNUMB	H4_IYEO_02_GNUMB,
  GNAME	H4_IYEO_03_GNAME,
  GPOSA	H4_IYEO_04_GPOSA,
  DATE1	H4_IYEO_05_DATE1,
  DATE2	H4_IYEO_06_DATE2,
  DATE3	H4_IYEO_07_DATE3,
  DATE4	H4_IYEO_08_DATE4,
  GBANG	H4_IYEO_09_GBANG,
  NAME1	H4_IYEO_10_NAME1,
  NAME2	H4_IYEO_11_NAME2,
  SCODE	H4_IYEO_12_SCODE,
  GRAT1	H4_IYEO_13_GRAT1,
  GOSUM	H4_IYEO_14_GOSUM,
  GSSUM	H4_IYEO_15_GSSUM,
  GBIGO	H4_IYEO_16_GBIGO,
  GMEMO	H4_IYEO_17_GMEMO
);


CREATE ASCENDING INDEX H4_IYEO_ ON H4_IYEO (ID);
CREATE ASCENDING INDEX H4_IYEO_HCODE ON H4_IYEO (HCODE);
CREATE ASCENDING INDEX H4_IYEO_GNUMB ON H4_IYEO (GNUMB);

CREATE GENERATOR H4_IYEO_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER H4_IYEO_ID_TNO FOR H4_IYEO 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(H4_IYEO_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;





/* Domain definitions */
CREATE DOMAIN H5_BANG_00_ID AS DOUBLE PRECISION
	  DEFAULT 0 NOT NULL;
CREATE DOMAIN H5_BANG_01_HCODE AS VARCHAR(5);
CREATE DOMAIN H5_BANG_02_GCODE AS VARCHAR(8);
CREATE DOMAIN H5_BANG_03_GNAME AS VARCHAR(24);
CREATE DOMAIN H5_BANG_04_GPOSA AS VARCHAR(10);
CREATE DOMAIN H5_BANG_05_GNUMB AS VARCHAR(24);
CREATE DOMAIN H5_BANG_06_GUBUN AS VARCHAR(20);
CREATE DOMAIN H5_BANG_07_GTELS AS VARCHAR(15);
CREATE DOMAIN H5_BANG_08_NAME1 AS VARCHAR(20);
CREATE DOMAIN H5_BANG_09_NAME2 AS VARCHAR(20);
CREATE DOMAIN H5_BANG_10_GDATE AS VARCHAR(10);
CREATE DOMAIN H5_BANG_11_CLASS AS DOUBLE PRECISION
	  DEFAULT 0;
CREATE DOMAIN H5_BANG_12_GSSUM AS DOUBLE PRECISION
	  DEFAULT 0;
CREATE DOMAIN H5_BANG_13_GSUSU AS DOUBLE PRECISION
	  DEFAULT 0;
CREATE DOMAIN H5_BANG_14_GMEMO AS TimeStamp;

/* Table: H5_BANG, Owner: SYSDBA */

CREATE TABLE H5_BANG 
(
  ID	H5_BANG_00_ID,
  HCODE	H5_BANG_01_HCODE,
  GCODE	H5_BANG_02_GCODE,
  GNAME	H5_BANG_03_GNAME,
  GPOSA	H5_BANG_04_GPOSA,
  GNUMB	H5_BANG_05_GNUMB,
  GUBUN	H5_BANG_06_GUBUN,
  GTELS	H5_BANG_07_GTELS,
  NAME1	H5_BANG_08_NAME1,
  NAME2	H5_BANG_09_NAME2,
  GDATE	H5_BANG_10_GDATE,
  CLASS	H5_BANG_11_CLASS,
  GSSUM	H5_BANG_12_GSSUM,
  GSUSU	H5_BANG_13_GSUSU,
  GMEMO	H5_BANG_14_GMEMO
);


CREATE ASCENDING INDEX H5_BANG_ ON H5_BANG (ID);
CREATE ASCENDING INDEX H5_BANG_HCODE ON H5_BANG (HCODE);
CREATE ASCENDING INDEX H5_BANG_GCODE ON H5_BANG (GCODE);

CREATE GENERATOR H5_BANG_ID_GEN;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER H5_BANG_ID_TNO FOR H5_BANG 
ACTIVE BEFORE INSERT POSITION 0
as
Begin
 New.ID = gen_id(H5_BANG_ID_GEN,1);
 New.GMEMO = current_timestamp;
End;
