#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Compare 12-screen-specification.csv Form rows to wireframes/{instance}.svg.

Writes: docs/phase1-structure/00-wireframe-coverage-gap.md

Run: python3 debug/report_wireframe_coverage_gap.py
"""
from __future__ import annotations

import csv
import io
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs" / "phase1-structure"
CSV12 = DOCS / "12-screen-specification.csv"
WF = DOCS / "wireframes"
OUT = DOCS / "00-wireframe-coverage-gap.md"


def read_csv_rows(path: Path) -> list[dict[str, str]]:
    raw = path.read_bytes()
    for enc in ("utf-8-sig", "utf-8", "cp949"):
        try:
            text = raw.decode(enc)
            break
        except UnicodeDecodeError:
            text = None
    else:
        text = raw.decode("utf-8", errors="replace")
    return list(csv.DictReader(io.StringIO(text)))


def main() -> int:
    if not CSV12.is_file():
        print(f"Missing {CSV12}", file=sys.stderr)
        return 1
    stems = {p.stem for p in WF.glob("*.svg")}
    rows = read_csv_rows(CSV12)
    forms = [r for r in rows if (r.get("kind") or "").strip() == "Form"]
    missing: list[str] = []
    present: list[str] = []
    for r in forms:
        inst = (r.get("instance") or "").strip()
        if not inst:
            continue
        if inst in stems:
            present.append(inst)
        else:
            missing.append(inst)

    lines: list[str] = []
    lines.append("# Wireframe coverage gap (Form vs SVG)\n\n")
    lines.append(
        "Generated by [`debug/report_wireframe_coverage_gap.py`](../../debug/report_wireframe_coverage_gap.py). "
        "Match rule: `wireframes/{instance}.svg` exists for each `kind=Form` row in "
        "[`12-screen-specification.csv`](12-screen-specification.csv).\n\n"
    )
    lines.append("## Summary\n\n")
    lines.append(f"| Metric | Count |\n|--------|------:|\n")
    lines.append(f"| Form rows in CSV | {len(forms)} |\n")
    lines.append(f"| With matching SVG | {len(present)} |\n")
    lines.append(f"| Missing SVG | {len(missing)} |\n\n")
    lines.append(
        "See also: [`figures/chart-wireframe-coverage.svg`](figures/chart-wireframe-coverage.svg) "
        "(from [`debug/generate_phase1_charts.py`](../../debug/generate_phase1_charts.py)).\n\n"
    )
    lines.append("## Forms without `wireframes/{instance}.svg`\n\n")
    if missing:
        for inst in sorted(missing):
            lines.append(f"- `{inst}`\n")
    else:
        lines.append("*(none)*\n")
    lines.append("\n## SVG files not referenced as Form instance\n\n")
    form_set = {(r.get("instance") or "").strip() for r in forms}
    orphan = sorted(stems - form_set)
    if orphan:
        for s in orphan:
            lines.append(f"- `{s}.svg`\n")
    else:
        lines.append("*(none)*\n")

    OUT.write_text("".join(lines), encoding="utf-8")
    print(f"Wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
